### ISSUE TITLE
When i click on the config button inside the mod menu the game crashes

### ISSUE THREAD

**Issue by alexHunter854** [Prospector/ModMenu#101]
When i click on the config button inside the menu the game crashes, it's on the modmenu-1.10.2+build.1.jar version (for 20w10a), but only for some mods e.g. diggusmaximus-1.2.6.jar ("Diggus Maximus") for the 1.16 snapshot, and, cmdkeybind-1.4.2.jar ("Command Macros") also for the 1.16 snapshot, if it helps their config files are jason5 and are made by the same modder, "Kyrptonaught".
 
here is my crash log if it helps

---- Minecraft Crash Report ----
// Why did you do that?

Time: 13:49 07/03/20
Description: Rendering screen

java.lang.NoSuchFieldError: active
	at net.kyrptonaught.cmdkeybind.config.clothconfig.ButtonEntry.render(ButtonEntry.java:36)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderList(DynamicEntryListWidget.java:432)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.method_25394(DynamicEntryListWidget.java:195)
	at me.shedaniel.clothconfig2.gui.widget.DynamicNewSmoothScrollingEntryListWidget.method_25394(DynamicNewSmoothScrollingEntryListWidget.java:110)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:377)
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:1003)
	at net.minecraft.class_310.method_1514(class_310.java:631)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.kyrptonaught.cmdkeybind.config.clothconfig.ButtonEntry.render(ButtonEntry.java:36)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderList(DynamicEntryListWidget.java:432)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.method_25394(DynamicEntryListWidget.java:195)
	at me.shedaniel.clothconfig2.gui.widget.DynamicNewSmoothScrollingEntryListWidget.method_25394(DynamicNewSmoothScrollingEntryListWidget.java:110)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:377)

-- Screen render details --
Details:
	Screen name: ~~NULL~~
	Mouse location: Scaled: (634, 59). Absolute: (1902.000000, 178.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['AlexHunter'/1, l='MpServer', x=-38.44, y=14.00, z=-63.72]]
	Chunk stats: Client Chunk Cache: 841, 552
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: -1033469979891055488
	Level generator: ID 03 - amplified, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-112,102,-144), Chunk: (at 0,6,0 in -7,-9; contains blocks -112,0,-144 to -97,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1862425 game time, 517748 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:431)
	at net.minecraft.class_310.method_1587(class_310.java:1966)
	at net.minecraft.class_310.method_1514(class_310.java:649)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w10a
	Minecraft Version ID: 20w10a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 962462088 bytes (917 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 1.2.4
		blue_endless_jankson: jankson +
		cloth: Cloth Events 2.0.0-unstable.202003051905
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 3.0.1-unstable.202003051928
		cmdkeybind: Command Macros 1.4.2
		diggusmaximus: Diggus Maximus 1.2.6
		fabric: Fabric API 0.5.1+build.305-1.16
		fabric-api-base: Fabric API Base 0.1.2+b7f9825dc4
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa5c4
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89c4
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825dc4
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+9421522dc4
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825dc4
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dc4
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+b1726571c4
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.10+2cbdd032c4
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825dc4
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.8+2cbdd032c4
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d6c4
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2c4
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825dc4
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6c4
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522dc4
		fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522dc4
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+b7d52fa5c4
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d6c4
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.7+9421522dc4
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+2f56dff2c4
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.25+2f56dff2c4
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60c4
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dc4
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed9c4
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490c4
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+53410490c4
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.11+b7d52fa5c4
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd91580c4
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba7c4
		fabricloader: Fabric Loader 0.7.8+build.186
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.16-alpha.20.10.a
		modmenu: Mod Menu 1.10.2+build.1
		phosphor: Phosphor 0.4.0
		roughlyenoughitems: Roughly Enough Items 4.0.7-unstable
		yet_another_gravestone_mod: Yet Another Gravestone Mod 1.2.2
	Launched Version: fabric-loader-0.7.8+build.186-20w10a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r587071.zip
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

**Comment by Prospector** [comment]
Looks like an error from Smooth Scrolling. Doesn't seem to have anything to do with Mod Menu though.

**Comment by alexHunter854** [comment]
Thanks!

‫בתאריך יום ו׳, 13 במרץ 2020 ב-3:18 מאת ‪Prospector‬‏ <‪
notifications@github.com‬‏>:‬
