### ISSUE TITLE
Trying to enter mod configuration through the Mod Menu mod crashes the game.

### ISSUE THREAD

**Issue by TheEmeraldBat** [Prospector/ModMenu#152]
I have been trying to use mods using the Fabric launcher yet simply trying to the configure mods will crash the game entirely.

Crash report;

Rendering screen

java.lang.ClassCastException: net.minecraft.class_5481$$Lambda$3318/1988053609 cannot be cast to net.minecraft.class_5348
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen$CategoryTextEntry.render(GlobalizedClothConfigScreen.java:398)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderItem(DynamicEntryListWidget.java:445)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:365)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:333)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderList(DynamicEntryListWidget.java:439)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderList(ClothConfigScreen.java:374)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.method_25394(DynamicEntryListWidget.java:200)
	at me.shedaniel.clothconfig2.gui.widget.DynamicNewSmoothScrollingEntryListWidget.method_25394(DynamicNewSmoothScrollingEntryListWidget.java:136)
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.method_25394(GlobalizedClothConfigScreen.java:185)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen$CategoryTextEntry.render(GlobalizedClothConfigScreen.java:398)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderItem(DynamicEntryListWidget.java:445)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:365)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:333)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderList(DynamicEntryListWidget.java:439)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderList(ClothConfigScreen.java:374)
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.method_25394(DynamicEntryListWidget.java:200)
	at me.shedaniel.clothconfig2.gui.widget.DynamicNewSmoothScrollingEntryListWidget.method_25394(DynamicNewSmoothScrollingEntryListWidget.java:136)
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.method_25394(GlobalizedClothConfigScreen.java:185)

-- Screen render details --
Details:
	Screen name: me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen
	Mouse location: Scaled: (659, 61). Absolute: (1318.000000, 122.000000)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1345917032 bytes (1283 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		fabric: Fabric API 0.18.0+build.397-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b4e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+02fb8fda4e
		fabricloader: Fabric Loader 0.9.1+build.205
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		roughlyenoughitems: Roughly Enough Items 4.12.0
	Launched Version: fabric-loader-0.9.1+build.205-1.16.2

**Comment by Prospector** [comment]
If I had to guess, you were probably using the wrong version of some mod, or something of that nature. Either way, nothing to do with Mod Menu, as the config screens are all the handling of other mods.
