### ISSUE TITLE
Game crashes when trying to open mod menu

### ISSUE THREAD

**Issue by TNTMaster5858** [Prospector/ModMenu#214]

**Comment by Prospector** [comment]
Need a log

**Comment by TNTMaster5858** [comment]
Wait a sec

**Comment by TNTMaster5858** [comment]
Sorry, need a few mintues

**Comment by Prospector** [comment]
Take your time

**Comment by TNTMaster5858** [comment]
The game crashed whilst mouseclicked event handler
Error: java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/ConfigEntryBuilder
Exit Code: -1

**Comment by coderbot16** [comment]
Can you attach the full log file? (`.minecraft/logs/latest.log`)

It would help because then we can see the versions of all of the mods loaded as well as the full crash trace.

**Comment by TNTMaster5858** [comment]
[18:27:06] [main/INFO]: Loading for game Minecraft 1.16.5
[18:27:06] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[18:27:09] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[18:27:09] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.2.0+daa38b3d7d, also found 0.2.0+9f0fb4b83a
[18:27:09] [main/INFO]: [FabricLoader] Loading 55 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.1, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, playerabilitylib@1.2.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, modmenu@1.16.5, fabric-command-api-v1@1.0.10+ca58154a7d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, angerable-patch@1.0.0-1.16.1, io_github_onyxstudios_cardinal-components-api@2.7.9, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, identity@1.11.4-beta-1.16.4, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, replaymod@1.16.4-2.5.1, autoconfig1u@3.2.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.7.9, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, cardinal-components-base@2.7.9, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[18:27:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/rkhw2/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[18:27:09] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[18:27:10] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[18:27:10] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[18:27:10] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[18:27:14] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:27:14] [main/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:625) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:409) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
[18:27:14] [main/INFO]: Setting user: Player
[18:27:14] [main/WARN]: WARNING! Mod playerabilitylib is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[18:27:14] [main/WARN]: WARNING! Mod replaymod is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[18:27:14] [main/WARN]: WARNING! Mod autoconfig1u is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[18:27:14] [main/WARN]: WARNING! Mod cardinal-components-entity is only using deprecated 'modmenu:parent' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[18:27:14] [main/WARN]: WARNING! Mod cardinal-components-entity is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[18:27:14] [main/WARN]: WARNING! Mod cardinal-components-base is only using deprecated 'modmenu:parent' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[18:27:14] [main/WARN]: WARNING! Mod cardinal-components-base is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[18:27:14] [main/INFO]: [Indigo] Registering Indigo renderer!
[18:27:15] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:27:17] [Thread-58/INFO]: Cannot offer OpenEye, server returned: 404 Not Found
[18:27:18] [main/INFO]: Narrator library for x64 successfully loaded
[18:27:18] [main/INFO]: Reloading ResourceManager: Default, replaymod_lang, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Pal, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Mod Menu, Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Identity, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Key Binding API (v1), Replay Mod, Auto Config v1 Updated, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[18:27:19] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:27:25] [main/INFO]: OpenAL initialized.
[18:27:25] [main/INFO]: Sound engine started
[18:27:25] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[18:27:25] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[18:27:25] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:27:25] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:27:25] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:27:25] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:27:25] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:27:26] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:27:26] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:27:26] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:27:31] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[18:27:31] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[18:27:31] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[18:27:31] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[18:27:31] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[18:27:31] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[18:27:31] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Identity)
[18:27:32] [main/INFO]: Loaded 7 recipes
[18:27:32] [main/INFO]: Loaded 927 advancements
[18:27:32] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 1.215 ms
[18:27:33] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:27:33] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[18:27:33] [Server thread/INFO]: Generating keypair
[18:27:35] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:27:35] [main/INFO]: Preparing spawn area: 0%
[18:27:36] [main/INFO]: Preparing spawn area: 0%
[18:27:36] [main/INFO]: Preparing spawn area: 4%
[18:27:37] [main/INFO]: Preparing spawn area: 9%
[18:27:37] [main/INFO]: Preparing spawn area: 15%
[18:27:38] [main/INFO]: Preparing spawn area: 22%
[18:27:38] [main/INFO]: Preparing spawn area: 29%
[18:27:39] [main/INFO]: Preparing spawn area: 34%
[18:27:39] [main/INFO]: Preparing spawn area: 43%
[18:27:40] [main/INFO]: Preparing spawn area: 43%
[18:27:40] [main/INFO]: Preparing spawn area: 52%
[18:27:41] [main/INFO]: Preparing spawn area: 65%
[18:27:41] [main/INFO]: Preparing spawn area: 73%
[18:27:42] [main/INFO]: Preparing spawn area: 79%
[18:27:42] [main/INFO]: Preparing spawn area: 91%
[18:27:43] [main/INFO]: Time elapsed: 7434 ms
[18:27:43] [Server thread/INFO]: Changing view distance to 11, from 10
[18:27:45] [Netty Local Client IO #0/INFO]: [CHAT] [Replay Mod] Recording started
[18:27:45] [Server thread/INFO]: Player[local:E:a28a6f72] logged in with entity id 245 at (-184.5, 67.0, -198.5)
[18:27:45] [Server thread/INFO]: Player joined the game
[18:27:46] [Server thread/INFO]: Saving and pausing game...
[18:27:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Demo World]'/minecraft:overworld
[18:27:46] [main/INFO]: Loaded 0 advancements
[18:27:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Demo World]'/minecraft:the_nether
[18:27:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Demo World]'/minecraft:the_end
[18:27:48] [Server thread/INFO]: Stopping server
[18:27:48] [Server thread/INFO]: Saving players
[18:27:48] [Server thread/INFO]: Player lost connection: Disconnected
[18:27:48] [Server thread/INFO]: Player left the game
[18:27:48] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:27:48] [Server thread/INFO]: Saving worlds
[18:27:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Demo World]'/minecraft:overworld
[18:27:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (Demo_World): All chunks are saved
[18:27:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Demo World]'/minecraft:the_nether
[18:27:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:27:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Demo World]'/minecraft:the_end
[18:27:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:27:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (Demo_World): All chunks are saved
[18:27:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:27:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:27:48] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:440) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312$$Lambda$3494/1194715097.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312$$Lambda$2840/667953797.invoke(Unknown Source) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1068) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/ConfigEntryBuilder
	at me.sargunvohra.mcmods.autoconfig1u.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:36) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:81) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigScreen(AutoConfig.java:71) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat.lambda$getModConfigScreenFactory$0(ExampleModMenuCompat.java:19) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat$$Lambda$5714/326861321.create(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:60) ~[modmenu-1.16.5.jar:?]
	at com.terraformersmc.modmenu.ModMenu$$Lambda$2515/442759658.create(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:43) ~[modmenu-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:118) ~[modmenu-1.16.5.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:325) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:922) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget$$Lambda$5576/446364279.onPress(Unknown Source) ~[?:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312$$Lambda$3495/1651852800.run(Unknown Source) ~[?:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	... 21 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.clothconfig2.api.ConfigEntryBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at me.sargunvohra.mcmods.autoconfig1u.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:36) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:81) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigScreen(AutoConfig.java:71) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat.lambda$getModConfigScreenFactory$0(ExampleModMenuCompat.java:19) ~[54b64246-4814-4519-b495-f067a1ee7e36.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat$$Lambda$5714/326861321.create(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:60) ~[modmenu-1.16.5.jar:?]
	at com.terraformersmc.modmenu.ModMenu$$Lambda$2515/442759658.create(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:43) ~[modmenu-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:118) ~[modmenu-1.16.5.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:325) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:922) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget$$Lambda$5576/446364279.onPress(Unknown Source) ~[?:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_312$$Lambda$3495/1651852800.run(Unknown Source) ~[?:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	... 21 more

**Comment by Prospector** [comment]
Try updating Auto Config: https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api/files/3095961

**Comment by coderbot16** [comment]
This appears to be an Auto Config bug, a work around is installing [Cloth Config v2](https://www.curseforge.com/minecraft/mc-mods/cloth-config).

https://github.com/shedaniel/AutoConfig/issues/29

**Comment by TNTMaster5858** [comment]
do i just move this file into my mods folder?

**Comment by Prospector** [comment]
Yes, install the one coderbot16 linked, ignore my last message.

**Comment by TNTMaster5858** [comment]
I tried it, the same error poped up again
