### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by InaneBlatherskite** [Prospector/ModMenu#228]
When I started Minecraft, it said ModMenu was causing issues. So I simply deleted it and tried again, and it's still giving me the same issue and I don't know why or what could be causing it :')

Crash Log:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2021-03-04 12:57:24 EST
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'modmenu'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zbd000$stopFabricInit(MinecraftClient:3360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    Suppressed: java.lang.NoClassDefFoundError: software/bernie/geckolib3/renderer/geo/GeoEntityRenderer
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
        at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
        at net.fabricmc.loader.EntrypointStorage$$Lambda$81/851765426.get(Unknown Source)
        at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
        ... 11 more
    Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib3.renderer.geo.GeoEntityRenderer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 25 more
Caused by: java.lang.NoClassDefFoundError: com/terraformersmc/modmenu/api/ModMenuApi
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
    at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
    at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
    at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
    at net.fabricmc.loader.EntrypointStorage$$Lambda$81/851765426.get(Unknown Source)
    at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
    at io.github.prospector.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:75)
    at io.github.prospector.modmenu.ModMenu$$Lambda$4741/1275163873.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at io.github.prospector.modmenu.ModMenu.onInitializeClient(ModMenu.java:74)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement$$Lambda$4632/147853486.accept(Unknown Source)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement$$Lambda$2479/1304678413.accept(Unknown Source)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: com.terraformersmc.modmenu.api.ModMenuApi
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 7640471768 bytes (7286 MB) / 9898557440 bytes (9440 MB) up to 10737418240 bytes (10240 MB)
  CPUs: 8
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader), Mod Menu (modmenu)
  Fabric Mods: advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
               autoconfig1u: Auto Config v1 Updated 3.3.1
               bettercaves: YUNG's Better Caves 1.16.5-1.1
               betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
               betterend: Better End 0.7.1-beta
               betterf3: BetterF3 1.1.2
               bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
               betternether: Better Nether 5.0.3
               betterthanmending: BetterThanMending 1.3.0
               betterweather: Better Weather 1.0.0
               biome_locator: Biome Locator 1.1.2
               biomemakeover: Biome Makeover 1.16.4-1.2.11
               blame: Blame 1.16.4-2.4.1
               blue_endless_jankson: jankson 1.1.2
               bowinfinityfix: Bow Infinity Fix rv9
               byg: BYG 1.1.6
               can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
               cardinal-components-base: Cardinal Components API (base) 2.7.10
               cardinal-components-block: Cardinal Components API (blocks) 2.7.9
               cardinal-components-chunk: Cardinal Components API (chunks) 2.7.4
               cardinal-components-entity: Cardinal Components API (entities) 2.7.10
               carrier: Carrier 1.7.4
               ce_foodstuffs: Common Expansion: Foodstuffs 1.1.3
               chainmail: Chainmail 0.5.0
               cinderscapes: Cinderscapes 1.3.0+build.51
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.11.14
               crookedcrooks: Crooked Crooks 1.3.3+1.16.4
               customportalapi: customportalapi 0.0.1-beta18-1.16
               daemonic: Daemonic 1.1.1
               damagetint: Damage tint 1.0.1
               darkness: True Darkness 1.6.58
               dawn: Dawn API 1.7
               desolation: Desolation 1.0.4.3
               dragonloot: DragonLoot 1.0.4
               ecotones: Ecotones 0.7.1
               eldritch_mobs: Eldritch Mobs 1.6.8
               enhancedcelestials: Enhanced Celestials 1.0.2
               expandedstorage: ExpandedStorage 5.6.33
               extraalchemy: Extra Alchemy 1.4.1
               fabric: Fabric API 0.30.0+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
               fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
               fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
               fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
               fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
               fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
               fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
               fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
               fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
               fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
               fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
               fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
               fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
               fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
               fabricloader: Fabric Loader 0.11.2
               fabricshieldlib: Fabric Shield Lib 1.3.5-1.16.5
               fallflyinglib: FallFlyingLib 1.1.0
               fiber: fiber 0.23.0-2
               flytre_lib: FlytreLib 0.2.8
               gobber2: Gobber2 2.3.49
               gravestones: Gravestones v1.9
               greater_eye: Greater Eye of Ender 1.1.5
               harvest_scythes: Harvest Scythes 1.0.7
               hotm: Heart of the Machine 1.16.3-0.1.7
               illuminations: Illuminations 1.4.4
               imm_ptl_core: Immersive Portals Core 0.65
               immersive_portals: Immersive Portals 0.65
               inmis: Inmis 2.1.2-1.16.4
               jankson: Jankson 3.0.1+j1.2.0
               java: Java HotSpot(TM) 64-Bit Server VM 8
               libcd: LibCapableData 3.0.3+1.16.3
               libstructure: LibStructure 1.5
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               maelstrom_library: Maelstrom Library 1.0-1.16.5
               mcdict: MCDict 2.0.1+1.16.4
               minecraft: Minecraft 1.16.4
               moborigins: Mob Origins 1.2.1
               mobrebirth: Mob Rebirth 9.0.2
               mobs_attempt_parkour: Mobs Attempt Parkour 0.2.2-1.16.5
               modmenu: Mod Menu 1.14.6+build.31
               moenchantments: Mo'Enchantments 1.13.8
               mooblooms: Mooblooms 1.4.0
               more_gems: More Gems 1.1.9
               moreshields: MoreShields 2.0.1
               mostructures: Mo' Structures 1.0.1+mc.1.16.4
               mythicmetals: Mythic Metals 0.9.6
               nbtcrafting: NBT Crafting 2.0.5+mc1.16.4
               nookbuild: NookBuild 1.4.0
               notenoughanimations: NotEnoughAnimations 1.1.0
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
               org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
               org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
               org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
               org_yaml_snakeyaml: snakeyaml 1.26
               origins: Origins 0.5.0
               origins-classes: Origins: Classes 1.1.0
               patchouli: Patchouli 1.16.4-50-FABRIC
               pehkui: Pehkui 1.6.2+1.16.3
               physicsmod: Physics Mod 1.0.0
               playerabilitylib: Pal 1.2.1
               polymorph: Polymorph 0.0.10-1.16.5
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               ringsofascension: Rings of Ascension 1.1.1
               roughlyenoughitems: Roughly Enough Items 5.8.7
               roughlyenoughitems-api: REI (API) 5.8.7
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.7
               roughlyenoughitems-runtime: REI (Runtime) 5.8.7
               ruined_equipment: Ruined Equipment 1.2.4
               sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
               shapes: Shapes 2.0.0+build.10
               silky_spawners: Silky Spawners 2.1.0+build.2-1.16
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.2
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.4
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.4
               terrestria: Terrestria 2.1.5+build.28
               the_bumblezone: The Bumblezone - Fabric 1.16.5-2.3.0
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               transliterationlib: TRansliterationLib 1.0.2
               traverse: Traverse null
               trinkets: Trinkets 2.6.7
               unforgivingvoid: Unforgiving Void 2.0.0
               vanguard: Vanguard 1.0.5
               waila: Hwyla 1.9.22
               wild_explorer: Wild Explorer 1.3.2
               xaerominimap: Xaero's Minimap 20.27.3
               yungsapi: YUNG's API 1.16.5-Fabric-2
               zoob: Monster Of The Ocean Depths 3.0.0
  Patchouli open book context: n/a
  Launched Version: 1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>

**Comment by Prospector** [comment]
Update Mod Menu
