### ISSUE TITLE
ModMenu Still showing after I removed from mods folder

### ISSUE THREAD

**Issue by LilCBay** [Prospector/ModMenu#250]
Mod menu is still acting like a mod even though I deleted it from my folder. 
I installed it, then I changed a couple settings and it crashed my world when I tried to create it.

I deleted it and it's Mods Icon was still showing up and crashing my worlds.

I restarted my laptop and removed it from my recycle bin, then started Minecraft but now it wouldn't even open.

Even if it didn't crash it (which I'm sure it did) it's still acting as a mod after I deleted it from my mods folder.

I dont know if there are more files it puts itself in, but I just deleted it from my mods folder.

                                                      ------Crash Report before restart------

---- Minecraft Crash Report -------- Minecraft Crash Report ----// My bad.
Time: 4/22/21 6:00 PMDescription: Starting integrated server
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_1132.<init>(class_1132.java:52) at net.minecraft.class_310.method_29603(class_310.java:1853) at net.minecraft.class_310$$Lambda$6504/575626996.apply(Unknown Source) at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:260) at net.minecraft.class_310.method_29610(class_310.java:1853) at net.minecraft.class_310.method_29607(class_310.java:1752) at net.minecraft.class_525.redirect$bgd000$redirectOnCreateLevel(class_525.java:1263) at net.minecraft.class_525.method_2736(class_525.java:298) at net.minecraft.class_525.method_19922(class_525.java:238) at net.minecraft.class_525$$Lambda$5101/768013881.onPress(Unknown Source) at net.minecraft.class_4185.method_25306(class_4185.java:33) at net.minecraft.class_4264.method_25348(class_4264.java:16) at net.minecraft.class_339.method_25402(class_339.java:149) at net.minecraft.class_4069.method_25402(class_4069.java:27) at net.minecraft.class_312.method_1611(class_312.java:92) at net.minecraft.class_312$$Lambda$4367/425428090.run(Unknown Source) at net.minecraft.class_437.method_25412(class_437.java:435) at net.minecraft.class_312.method_1601(class_312.java:92) at net.minecraft.class_312.method_22686(class_312.java:162) at net.minecraft.class_312$$Lambda$4366/773099602.run(Unknown Source) at net.minecraft.class_1255.execute(class_1255.java:94) at net.minecraft.class_312.method_22684(class_312.java:162) at net.minecraft.class_312$$Lambda$3665/411990170.invoke(Unknown Source) at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) at org.lwjgl.system.JNI.invokeV(Native Method) at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) at net.minecraft.class_310.method_1523(class_310.java:1071) at net.minecraft.class_310.method_1514(class_310.java:681) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [autoswap.mixins.json:MixinServerPlayerInteractionManager] from phase [DEFAULT] in config [autoswap.mixins.json] FAILED during APPLY at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ... 43 moreCaused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on beforeUseOnBlock could not find any targets matching 'Lnet/minecraft/class_3225;method_14262(Lnet/minecraft/class_1657;Lnet/minecraft/class_1937;Lnet/minecraft/class_1799;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269;' in net.minecraft.class_3225. Using refmap AutoSwap-refmap.json [PREINJECT Applicator Phase -> autoswap.mixins.json:MixinServerPlayerInteractionManager -> Prepare Injections ->  -> handler$zzd000$beforeUseOnBlock(Lnet/minecraft/class_1657;Lnet/minecraft/class_1937;Lnet/minecraft/class_1799;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse] at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:422) at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_1132.<init>(class_1132.java:52) at net.minecraft.class_310.method_29603(class_310.java:1853) at net.minecraft.class_310$$Lambda$6504/575626996.apply(Unknown Source) at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:260)
-- Starting integrated server --Details: Level ID: REAL WORLDY WORLD!!!!!!!!!!!!!!! Level Name: REAL WORLDY WORLD!!!!!!!!!!!!!!!Stacktrace: at net.minecraft.class_310.method_29610(class_310.java:1853) at net.minecraft.class_310.method_29607(class_310.java:1752) at net.minecraft.class_525.redirect$bgd000$redirectOnCreateLevel(class_525.java:1263) at net.minecraft.class_525.method_2736(class_525.java:298) at net.minecraft.class_525.method_19922(class_525.java:238) at net.minecraft.class_525$$Lambda$5101/768013881.onPress(Unknown Source) at net.minecraft.class_4185.method_25306(class_4185.java:33) at net.minecraft.class_4264.method_25348(class_4264.java:16) at net.minecraft.class_339.method_25402(class_339.java:149) at net.minecraft.class_4069.method_25402(class_4069.java:27) at net.minecraft.class_312.method_1611(class_312.java:92) at net.minecraft.class_312$$Lambda$4367/425428090.run(Unknown Source)
-- Affected screen --Details: Screen name: net.minecraft.class_525Stacktrace: at net.minecraft.class_437.method_25412(class_437.java:435) at net.minecraft.class_312.method_1601(class_312.java:92) at net.minecraft.class_312.method_22686(class_312.java:162) at net.minecraft.class_312$$Lambda$4366/773099602.run(Unknown Source) at net.minecraft.class_1255.execute(class_1255.java:94) at net.minecraft.class_312.method_22684(class_312.java:162) at net.minecraft.class_312$$Lambda$3665/411990170.invoke(Unknown Source) at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) at org.lwjgl.system.JNI.invokeV(Native Method) at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) at net.minecraft.class_310.method_1523(class_310.java:1071) at net.minecraft.class_310.method_1514(class_310.java:681) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-- System Details --Details: Minecraft Version: 1.16.5 Minecraft Version ID: 1.16.5 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 1080788344 bytes (1030 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) CPUs: 4 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  adorn: Adorn 1.13.0+1.16.5 advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9 autofish: Autofish 0.9.2 autoswap: AutoSwap 0.2.0 betterdroppeditems: Better Dropped Items 1.2.4-1.16.2 bonappetit: Bon Appétit 0.8.5-3 campanion: Campanion 1.3.5 cardinal-components-base: Cardinal Components API (base) 2.7.5 cardinal-components-entity: Cardinal Components API (entities) 2.7.5 carrier: Carrier 1.7.5 chainmail: Chainmail 0.5.0 charm: Charm 2.3.2 cloth-basic-math: Cloth Basic Math 0.5.1 cloth-client-events-v0: Cloth Client Events v0 1.5.47 cloth-config2: Cloth Config v4 4.11.15 com_electronwill_night-config_core: core 3.6.2 com_electronwill_night-config_toml: toml 3.6.2 com_moandjiezana_toml_toml4j: toml4j 0.7.2 croptopia: Croptopia 1.3.1 expandedstorage: ExpandedStorage 5.6.33 fabric: Fabric API 0.33.0+1.16 fabric-api-base: Fabric API Base 0.2.1+9354966b7d fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d fabricloader: Fabric Loader 0.11.3 imm_ptl_core: Immersive Portals Core 0.90 immersive_portals: Immersive Portals 0.90 inmis: Inmis 2.2.1-1.16.5 inventoryhud: Inventory HUD + 3.2.2 invisframes: Invisible Frames 2.0.1 jankson: Jankson 3.0.1+j1.2.0 java: Java HotSpot(TM) 64-Bit Server VM 8 libcd: LibCapableData 3.0.3+1.16.3 libgui: LibGui 3.3.2+1.16.4 lithium: Lithium 0.6.4 microconfig: Microconfig 1.0.5 minecraft: Minecraft 1.16.5 modmenu: Mod Menu v1.16.8+unknown.bd9230a omega-config: OmegaConfig 1.0.2 org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31 org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31 org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31 org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31 org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2 org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0 org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0 phosphor: Phosphor 0.7.1+build.11 playerabilitylib: Pal 1.2.1 reach-entity-attributes: Reach Entity Attribute 1.0.1 roughlyenoughitems: Roughly Enough Items 5.11.218 roughlyenoughitems-api: REI (API) 5.11.218 roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218 roughlyenoughitems-runtime: REI (Runtime) 5.11.218 simple_backpack: SimpleBackpack 1.0.38 timeinabottle: Time in a Bottle 1.2-mc1.16.4-fabric vafoen: Vanilla Food Enhanced 1.1.1 waila: Hwyla 1.9.22 worldedit: WorldEdit 7.2.4+5723-e3bfc64 Launched Version: fabric-loader-0.11.3-1.16.5 Backend library: LWJGL version 3.2.2 build 10 Backend API: AMD Radeon(TM) R4 Graphics GL version 4.5.13469 Compatibility Profile Context 21.19.512.0, ATI Technologies Inc. GL Caps: Using framebuffer using OpenGL 3.0 Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric' Type: Client (map_client.txt) Graphics mode: fancy Resource Packs: file/bic-resource-pack-1-16-i5.zip, vanilla Current Language: English (US) CPU: 4x AMD A6-7310 APU with AMD Radeon R4 Graphics 

                                                                   ------Logs After restart------

 [16:10:30] [main/INFO]: Loading for game Minecraft 1.16.5
[16:10:32] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "C:\Users\toome\AppData\Roaming\.minecraft\mods\OptiFine_1.16.5_HD_U_G7.jar", ignoring
[16:10:33] [main/INFO]: [FabricLoader] Loading 82 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.11.218, fabricloader@0.11.3, fabric-structure-api-v1@1.1.4+ca58154a7d, autoswap@0.2.0, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, mm@2.2, campanion@1.3.5, fabric-textures-v0@1.0.6+ca58154a7d, com_electronwill_night-config_core@3.6.2, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, reach-entity-attributes@1.0.1, com_moandjiezana_toml_toml4j@0.7.2, playerabilitylib@1.2.1, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, simple_backpack@1.0.38, fabric-renderer-registries-v1@2.3.0+2868a2287d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.33.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, roughlyenoughitems-default-plugin@5.11.218, minecraft@1.16.5, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, jankson@3.0.1+j1.2.0, timeinabottle@1.2-mc1.16.4-fabric, microconfig@1.0.5, fabric-screen-api-v1@1.0.0+c045166c7d, betterdroppeditems@1.2.4-1.16.2, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, roughlyenoughitems-runtime@5.11.218, autofish@0.9.2, cloth-client-events-v0@1.5.47, com_electronwill_night-config_toml@3.6.2, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, roughlyenoughitems@5.11.218, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, croptopia@1.3.1, fabric-rendering-v1@1.6.0+2868a2287d, fabric-key-binding-api-v1@1.0.4+9354966b7d, cloth-config2@4.8.3, fabric-resource-loader-v0@0.4.6+2868a2287d, inventoryhud@3.2.2, chainmail@0.5.0, bonappetit@0.8.5-3, fabric-content-registries-v0@0.2.1+ca58154a7d, expandedstorage@5.6.33, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.4+5723-e3bfc64, fabric-biome-api-v1@3.1.1+ca58154a7d, optifabric@1.9.6, cardinal-components-entity@2.7.5, advanced_runtime_resource_pack@0.2.9, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, cardinal-components-base@2.7.5, invisframes@2.0.1, fabric-mining-levels-v0@0.1.3+ca58154a7d, carrier@1.7.5, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, charm@2.3.2, fabric-models-v0@0.3.0+bc7a746f7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-object-builders-v0@0.7.2+ca58154a7d

I also am aware that I'm using Campanion and OptiFabric together but its has worked before and I really just use the backpacks and the grappling hook instead of tents.

------Logs where modmenu is still showing up after it was deleted and I replaced optifabric with Sodium, Lithium, and Phosphor----

[16:18:45] [main/INFO]: Loading for game Minecraft 1.16.5
[16:18:48] [main/INFO]: [FabricLoader] Loading 86 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.11.218, fabricloader@0.11.3, fabric-structure-api-v1@1.1.4+ca58154a7d, autoswap@0.2.0, lithium@0.6.4, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, campanion@1.3.5, fabric-textures-v0@1.0.6+ca58154a7d, com_electronwill_night-config_core@3.6.2, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, reach-entity-attributes@1.0.1, com_moandjiezana_toml_toml4j@0.7.2, playerabilitylib@1.2.1, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, sodium@0.1.0, simple_backpack@1.0.38, fabric-renderer-registries-v1@2.3.0+2868a2287d, immersive_portals@0.90, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.33.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, imm_ptl_core@0.90, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, roughlyenoughitems-default-plugin@5.11.218, minecraft@1.16.5, modmenu@v1.16.8+unknown.bd9230a, fabric-command-api-v1@1.1.1+351679a77d, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, timeinabottle@1.2-mc1.16.4-fabric, microconfig@1.0.5, phosphor@0.7.1+build.11, fabric-screen-api-v1@1.0.0+c045166c7d, betterdroppeditems@1.2.4-1.16.2, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, roughlyenoughitems-runtime@5.11.218, autofish@0.9.2, cloth-client-events-v0@1.5.47, com_electronwill_night-config_toml@3.6.2, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, roughlyenoughitems@5.11.218, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, croptopia@1.3.1, fabric-rendering-v1@1.6.0+2868a2287d, fabric-key-binding-api-v1@1.0.4+9354966b7d, cloth-config2@4.11.15, fabric-resource-loader-v0@0.4.6+2868a2287d, inventoryhud@3.2.2, chainmail@0.5.0, bonappetit@0.8.5-3, fabric-content-registries-v0@0.2.1+ca58154a7d, expandedstorage@5.6.33, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.4+5723-e3bfc64, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.7.5, advanced_runtime_resource_pack@0.2.9, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, cardinal-components-base@2.7.5, invisframes@2.0.1, fabric-mining-levels-v0@0.1.3+ca58154a7d, carrier@1.7.5, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, charm@2.3.2, fabric-models-v0@0.3.0+bc7a746f7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-object-builders-v0@0.7.2+ca58154a7d
[16:18:48] [main/WARN]: Mod `modmenu` (v1.16.8+unknown.bd9230a) does not respect SemVer - comparison support is limited.

I have cleared my Mods folder and selected certain ones very carefully back in but its not working.

I have also reinstalled my fabricinstaller.exe but still nothing.

My email is chast980@gmail.com but I don't really check it much.

I'm aware about the discord server but I don't really use discord.

I just need instructions on how to delete it and get rid of it for good I don't really need the menu.

**Comment by jackassmc** [comment]
If ModMenu isn't loaded from the mods folder it is loaded from inside another mod.

To find out which mod includes ModMenu remove all mods and readd them until ModMenu is loaded again.
