### ISSUE TITLE
Game crashes while configuring the BetterF3 mod [1.17]

### ISSUE THREAD

**Issue by JoostVisser7** [Prospector/ModMenu#265]
I'm not quite sure if I should report this bug to this forum or the BetterF3 forum, so I'm reporting it to both. 

While trying to edit the BetterF3 configs, the game crashes because the Narrator doesn't understand something in the menu. Full crash report below. I'm surprised this crash happened at all because I have the narrator turned off. The crash happens a few seconds after opening either the "Left Modules" or the "Right Modules" window in the BetterF3 configuration menu. The "General Settings" window does not seem to be affected.

Crash Report:

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/06/2021, 12:42
Description: Narrating screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.getString()" because "â˜ƒ" is null
	at net.minecraft.class_6382.method_37034(class_6382.java:8)
	at net.minecraft.class_4280$class_4281.method_37020(class_4280.java:63)
	at net.minecraft.class_4280.method_37020(class_4280.java:40)
	at net.minecraft.class_437.method_37056(class_437.java:593)
	at net.minecraft.class_437.method_37062(class_437.java:576)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:566)
	at net.minecraft.class_437.method_37071(class_437.java:553)
	at net.minecraft.class_757.method_3192(class_757.java:890)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_6382.method_37034(class_6382.java:8)
	at net.minecraft.class_4280$class_4281.method_37020(class_4280.java:63)
	at net.minecraft.class_4280.method_37020(class_4280.java:40)
	at net.minecraft.class_437.method_37056(class_437.java:593)
	at net.minecraft.class_437.method_37062(class_437.java:576)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:566)
	at net.minecraft.class_437.method_37071(class_437.java:553)

-- Screen details --
Details:
	Screen name: me.cominixo.betterf3.config.gui.modules.ModulesScreen

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Vanilla Tweaks 1.17_01.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 501406328 bytes (478 MiB) / 1778384896 bytes (1696 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3,80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6627
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19658,62
	Virtual memory used (MB): 12123,22
	Swap memory total (MB): 3328,00
	Swap memory used (MB): 285,00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 1.1.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.33
		easiervillagertrading: EasierVillagerTrading 1.17-fabric0.34.9-1.5.3
		fabric: Fabric API 0.34.9+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b4463d5
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13d5
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b4463d5
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463d5
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afad5
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b4463d5
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b4463d5
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da310d5
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b4463d5
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b4463d5
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b4463d5
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afad5
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b4463d5
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab6121d5
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463d5
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ed5
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b4463d5
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afad5
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b4463d5
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121d5
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b4463d5
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b4463d5
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b4463d5
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b4463d5
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+a02b4463d5
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b4463d5
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b4463d5
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afad5
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b4463d5
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.3+b7ab6121d5
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463d5
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.10+be9da310d5
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b4463d5
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabricloader: Fabric Loader 0.11.3
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17
		modmenu: Mod Menu 2.0.0-beta.7
	Launched Version: fabric-loader-0.11.3-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 466.27, NVIDIA Corporation
	Window size: 1920x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Vanilla Tweaks 1.17_01.zip
	Current Language: English (United Kingdom)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
```

**Comment by jackassmc** [comment]
This was fixed in https://github.com/cominixo/BetterF3/commit/cafde8ebc7162200222bf2ee809746f5cc2b9f4a / BetterF3 `v1.1.5`.
