### ISSUE TITLE
Opening Mod Menu after Startup causes Minecraft to crash [modmenu-2.0.2 1.17]

### ISSUE THREAD

**Issue by Mistyttm** [Prospector/ModMenu#273]
`[20:13:23] [main/INFO]: Loading for game Minecraft 1.17
[20:13:29] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "C:\Users\elija\AppData\Roaming\.minecraft\mods\preview_OptiFine_1.17_HD_U_G9_pre21.jar", ignoring
[20:13:29] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+c88702897d
 - Mod 'EasierVillagerTrading' (easiervillagertrading) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+198a96213d, also found 1.0.4+155f865c3d
 - Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121a0, also found 0.4.7+b7ab61213d, 0.4.7+b7ab6121d5
 - Mod 'BetterF3' (betterf3) recommends version 2.0.0.* of mod 'Mod Menu' (modmenu), but a non-matching version is present: 2.0.2!
	 - You must install version 2.0.0.* of 'Mod Menu' (modmenu).
	 - Mod 'Mod Menu' (modmenu) v2.0.2 is being loaded from the user's mod directory.
[20:13:29] [main/INFO]: [FabricLoader] Loading 81 mods: fabric-renderer-api-v1@0.4.3+676f40fa3d, craftpresence@1.8.2, fabric-keybindings-v0@0.2.2+36b77c3e3d, cloth-common-events-v1@2.0.54, fabricloader@0.11.3, fabric-structure-api-v1@1.1.11+e36969833d, fabric-containers-v0@0.1.12+a02b44633d, fabric-object-builder-api-v1@1.10.9+b7ab61213d, fabric-dimensions-v1@2.0.10+a02b44633d, java@16, fabric-game-rule-api-v1@1.0.6+a02b44633d, fabric-api-base@0.3.0+a02b44633d, mm@2.1, fabric-rendering-data-attachment-v1@0.1.5+a02b44633d, textbook@1.1.0+1.16.5, fiber@0.23.0-2, fabric-textures-v0@1.0.6+a02b44633d, fabric-rendering-fluids-v1@0.1.13+a02b44633d, cloth-scissors-api-v1@2.0.54, litematica@0.0.0-dev.20210614.175836, easiervillagertrading@1.17-fabric0.34.9-1.5.3, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, fabric-lifecycle-events-v1@1.4.4+a02b44633d, fabric-renderer-registries-v1@3.2.0+a02b44633d, chat_heads@0.2.2+1.16.2, dynmus@1.3.0, fabric-loot-tables-v1@1.0.4+a02b44633d, fabric@0.35.2+1.17, fabric-particles-v1@0.2.4+a02b44633d, org_codehaus_groovy_groovy@3.0.8, pling@1.3.0, fabric-networking-v0@0.3.2+92519afa3d, fabric-api-lookup-api-v1@1.1.0+1d383bb63d, okzoomer@5.0.0-beta.1+21w03a, fabric-screen-handler-api-v1@1.1.8+a02b44633d, fabric-networking-blockentity-v0@0.2.11+a02b44633d, minecraft@1.17, fireplacelib@3.3.0+1.17, modmenu@2.0.2, fabric-command-api-v1@1.1.1+a02b44633d, eggtab@2.1.0+1.16-fabric, cloth-basic-math@0.5.1, musicdr@1.2.1, cloth-utils-v1@2.0.54, fabric-screen-api-v1@1.0.4+198a96213d, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, fabric-renderer-indigo@0.4.8+a02b44633d, cloth-client-events-v0@2.0.54, fabric-item-api-v1@1.2.4+a02b44633d, fabric-events-interaction-v0@0.4.8+a02b44633d, fabric-crash-report-info-v1@0.1.5+be9da3103d, slight-gui-modifications@2.0.0, libzoomer@0.1.0+21w03a, fabric-entity-events-v1@1.1.0+a02b44633d, fabric-rendering-v0@1.1.2+92519afa3d, fabric-rendering-v1@1.6.0+a02b44633d, fabric-key-binding-api-v1@1.0.4+a02b44633d, cloth-config2@5.0.34, smoothscrollingeverywhere@3.0.3-unstable, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.4.7+b7ab6121a0, malilib@0.10.0+dev.22, fabric-content-registries-v0@0.2.2+a02b44633d, fabric-tag-extensions-v0@1.1.4+a02b44633d, fabric-biome-api-v1@3.1.11+c345aea83d, advanced_runtime_resource_pack@0.4.3, architectury@2.0.7, cloth-api@2.0.54, fabric-registry-sync-v0@0.7.10+e2961fee3d, fabric-commands-v0@0.2.2+92519afa3d, authme@1.5.0, damagetilt@1.17-fabric-0.1.2, fabric-mining-levels-v0@0.1.3+92519afa3d, betterf3@1.1.3, cloth-datagen-api-v1@2.0.54, fabric-networking-api-v1@1.0.11+b7ab61213d, fabric-events-lifecycle-v0@0.2.1+92519afa3d, org_codehaus_groovy_groovy-jsr223@3.0.8, fabric-models-v0@0.3.0+a02b44633d, fabric-item-groups-v0@0.2.10+b7ab61213d, fabric-object-builders-v0@0.7.3+a02b44633d
[20:13:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/elija/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[20:13:31] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[20:13:31] [main/INFO]: Compatibility level set to JAVA_16
[20:13:35] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[20:13:36] [main/INFO]: I used the json to destroy the json
[20:14:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:14:09] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationException: com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/privileges due to Read timed out
	at com.mojang.authlib.exceptions.MinecraftClientException.toAuthenticationException(MinecraftClientException.java:28) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:116) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:42) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:151) ~[authlib-2.3.31.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:672) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:431) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/privileges due to Read timed out
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar:?]
	... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:976) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:422) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:574) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:64) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar:?]
	... 12 more
[20:14:19] [Render thread/INFO]: Setting user: Misty_TTM
[20:14:19] [Render thread/INFO]: Definitely not up to no good
[20:14:19] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zii000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:14:59] [Render thread/INFO]: [STDOUT]: Music Duration Reuder is loaded, will prioritize Dynamic Music pitch settings over Music Duration Reducer
[20:15:02] [CraftPresence/INFO]: Received update status for craftpresence -> Release (Target version: v1.8.2)
[20:15:02] [CraftPresence/INFO]: Configuration settings have been saved and reloaded successfully!
[20:15:02] [CraftPresence/INFO]: Checking for valid Curse manifest data...
[20:15:02] [CraftPresence/INFO]: Failed to find primary Curse manifest data, attempting to use fallback resource...
[20:15:02] [CraftPresence/ERROR]: Unable to get Curse manifest data (ignore if not using a Twitch/CursePack)
[20:15:02] [CraftPresence/INFO]: Checking for valid MultiMC instance data...
[20:15:02] [CraftPresence/ERROR]: Unable to get MultiMC instance data (ignore if not using a MultiMC Pack)
[20:15:02] [CraftPresence/INFO]: Checking for valid MCUpdater instance data...
[20:15:02] [CraftPresence/ERROR]: Unable to get MCUpdater instance data (ignore if not using a MCUpdater Pack)
[20:15:02] [CraftPresence/INFO]: Checking for valid Technic pack data...
[20:15:02] [CraftPresence/ERROR]: Unable to get Technic pack data (ignore if not using a Technic Pack)
[20:15:02] [CraftPresence/INFO]: Checking Discord for available assets with Client Id: 450485984333660181
[20:15:02] [CraftPresence/INFO]: Originally coded by paulhobbel - https://github.com/paulhobbel
[20:15:06] [Render thread/WARN]: WARNING! Mod craftpresence is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[20:15:06] [Render thread/WARN]: WARNING! Mod mm is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[20:15:06] [Render thread/WARN]: WARNING! Mod fiber is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[20:15:06] [Render thread/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[20:15:06] [Render thread/WARN]: WARNING! Mod smoothscrollingeverywhere is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[20:15:06] [Render thread/WARN]: WARNING! Mod autoconfig1u is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[20:15:06] [Render thread/WARN]: WARNING! Mod malilib is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[20:15:06] [Render thread/WARN]: WARNING! Mod architectury is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[20:15:06] [Render thread/INFO]: [Egg Tab] Moving already registered items
[20:15:06] [Render thread/INFO]: [Egg Tab] Moved 67 items to itemGroup.eggtab.egg_group
[20:15:06] [Render thread/INFO]: [Egg Tab] Moved 0 items to Foodstuffs
[20:15:06] [Render thread/INFO]: [Egg Tab] Now listening for new items
[20:15:06] [Render thread/INFO]: [Egg Tab] Moving enchanted books
[20:15:06] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[20:15:09] [CraftPresence/INFO]: 77 total assets detected!
[20:15:11] [Thread-84/INFO]: Start Loading of CTS.
[20:15:13] [Render thread/INFO]: [BetterF3] Loading...
[20:15:13] [Render thread/INFO]: [BetterF3] All done!
[20:15:14] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[20:15:30] [Thread-84/INFO]: Hello From 'Slight' Gui Modifications cts script
[20:15:33] [CraftPresence/INFO]: Loaded display data with Client Id: 450485984333660181 (Logged in as _s.u.soup_)
[20:15:48] [Render thread/WARN]: Removed resource pack file/VanillaTweaks_r576208.zip from options because it doesn't seem to exist anymore
[20:15:48] [Render thread/WARN]: Removed resource pack file/3.0.1v_VisualEnchantments from options because it doesn't seem to exist anymore
[20:15:50] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:15:51] [Render thread/INFO]: Reloading ResourceManager: Default, Spiders BE GONE, improved netherite, The Gayest Pack to Ever be Concieved, Fabric Mods (Fabric Renderer API (v1), CraftPresence, Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Dimensions API (v1), Fabric Game Rule API (v1), Fabric API Base, Manningham Mills, Fabric Rendering Data Attachment (v1), Textbook, Fabric Textures (v0), Fabric Rendering Fluids (v1), Litematica, EasierVillagerTrading, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Chat Heads, Dynamic Music, Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Pling, Fabric Networking (v0), Fabric API Lookup API (v1), Ok Zoomer, Fabric Screen Handler API (v1), Fabric Networking Block Entity (v0), Fireplace Lib, Mod Menu, Fabric Command API (v1), Egg Tab, Music Duration Reducer, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), 'Slight' GUI Modifications, LibZoomer, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Key Binding API (v1), Cloth Config v4, Smooth Scrolling Everywhere, Auto Config v1 Updated, Fabric Resource Loader (v0), MaLiLib, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Runtime Resource Pack, Fabric Registry Sync (v0), Fabric Commands (v0), Auth Me, Damage Tilt, Fabric Mining Levels (v0), BetterF3, Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0))
[20:15:51] [Render thread/INFO]: ARRP register - before vanilla
[20:15:51] [Render thread/INFO]: ARRP register - after vanilla
[20:15:52] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:52] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:15:55] [CraftPresence/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 6.062 ms
[20:15:56] [Render thread/INFO]: [Ok Zoomer] nmn what's this
[20:17:07] [Worker-Main-4/WARN]: Unused frames in sprite minecraft:block/crimson_nylium: [15, 16, 17, 18, 19, 20, 21, 22]
[20:17:07] [Worker-Main-4/WARN]: Unused frames in sprite minecraft:block/crimson_nylium_side: [15, 16, 17, 18, 19, 20, 21, 22]
[20:17:08] [Worker-Main-4/WARN]: Unused frames in sprite minecraft:block/nether_gold_ore: [15, 16, 17, 18, 19, 20, 21, 22]
[20:17:08] [Worker-Main-4/WARN]: Unused frames in sprite minecraft:block/nether_quartz_ore: [15, 16, 17, 18, 19, 20, 21, 22]
[20:17:08] [Worker-Main-4/WARN]: Unused frames in sprite minecraft:block/netherrack: [15, 16, 17, 18, 19, 20, 21, 22]
[20:17:09] [Worker-Main-4/WARN]: Unused frames in sprite minecraft:block/warped_nylium_side: [15, 16, 17, 18, 19, 20, 21, 22]
[20:17:18] [Render thread/INFO]: 'language' is an unsupported metadata key!
[20:17:18] [Render thread/WARN]: Skipped language file: minecraft:lang/en_us.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 128 column 2 path $.commands.save.success)
[20:17:29] [Render thread/INFO]: OpenAL initialized.
[20:17:29] [Render thread/INFO]: Sound engine started
[20:17:30] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[20:17:30] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[20:17:30] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[20:17:30] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[20:17:30] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[20:17:30] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[20:17:30] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:17:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:17:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:17:38] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:17:44] [Render thread/ERROR]: Invalid locale: en_au, defaulting to en_us.
[20:17:44] [Render thread/ERROR]: Error from mod 'fireplacelib'
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:167) ~[?:?]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:108) ~[?:?]
	at dev.the_fireplace.lib.impl.translation.LanguageMap.getLangJsonElement(LanguageMap.java:47) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.translation.LanguageMap.<init>(LanguageMap.java:29) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.translation.ModLanguageMaps.lambda$getPrimaryMap$0(ModLanguageMaps.java:13) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at dev.the_fireplace.lib.impl.translation.ModLanguageMaps.getPrimaryMap(ModLanguageMaps.java:13) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.translation.I18n.hasPrimaryTranslation(I18n.java:26) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.translation.I18n.translateToLocalFormatted(I18n.java:14) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.translation.TranslatorManagerImpl$TranslatorImpl.getTranslatedText(TranslatorManagerImpl.java:68) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.api.client.ConfigScreenBuilder.addStringField(ConfigScreenBuilder.java:42) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.api.client.ConfigScreenBuilder.addStringField(ConfigScreenBuilder.java:30) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.config.FLModMenuIntegration.addGlobalCategoryEntries(FLModMenuIntegration.java:51) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.config.FLModMenuIntegration.buildConfigCategories(FLModMenuIntegration.java:47) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at dev.the_fireplace.lib.impl.config.FLModMenuIntegration.lambda$getModConfigScreenFactory$1(FLModMenuIntegration.java:35) ~[Fireplace-Lib-3.3.0+1.17.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:52) ~[modmenu-2.0.2.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:122) ~[modmenu-2.0.2.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:387) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:986) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-2.0.2.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:311) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1139) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[20:17:55] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:884) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1114) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.shadeModel(int)'
	at net.minecraft.class_350.handler$zom000$renderScrollbar(class_350.java:1687) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:266) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:278) ~[modmenu-2.0.2.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:875) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	... 10 more
[20:17:55] [CraftPresence-ShutDown-Handler/INFO]: Shutting down CraftPresence...`

**Comment by Mistyttm** [comment]
Fixed the issue. An outdated mod was causing the crash

**Comment by triphora** [comment]
For anyone else coming across this issue, the "outdated mod" is Smooth Scrolling Everywhere.

@Mistyttm, for future reference: [please share your actual solution, don't just say "an outdated mod"!](https://xkcd.com/979/)
