### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by efffauw** [Prospector/ModMenu#375]
<details>
<summary>Crash Log</summary>

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/12/21, 4:03 PM
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "io.github.jamalam360.notify.resolver.NotifyVersionChecker$VersionComparisonResult.name()" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.handler$cjm000$notify$appendNotifyStatus(DescriptionListWidget.java:577)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.render(DescriptionListWidget.java:104)
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:278)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.handler$cjm000$notify$appendNotifyStatus(DescriptionListWidget.java:577)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.method_25394(DescriptionListWidget.java:104)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:278)

-- Screen render details --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
	Mouse location: Scaled: (135, 151). Absolute: (270.000000, 303.000000)
	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, potion-of-undying.zip, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, additionalbars/classic, Overlay-Textures-§61.17§r (1).zip, beans-e2211.zip, lambdabettergrass/default, VanillaTweaks_r135727.zip, VisibleOres2.2.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1502370808 bytes (1432 MiB) / 2013265920 bytes (1920 MiB) up to 4194304000 bytes (4000 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=27.20.11044.5003
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18386.77
	Virtual memory used (MB): 12768.88
	Swap memory total (MB): 12295.16
	Swap memory used (MB): 0.00
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx4000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.0
		additionalbars: Additional Bars 2.2.0
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		afkpeace: AFKPeace 4.6.5
		alloy_forgery: Alloy Forgery 2.0.7+1.18
		amecsapi: Amecs API 1.3.2+mc1.18-pre1
		amethystequipment: Amethyst Equipment 1.18
		amplified_nether: Amplified Nether for Fabric 1.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.2+1.18
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.3
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.0
		architectury: Architectury 3.1.45
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.2.3
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.1.0+0
		bcdt_expansion: BCDT Expansion 1.18-1.0.0
		betterthirdperson: Better Third Person 1.5.4
		biomeinfo: Biome Info 1.18-8
		blockus: Blockus 2.3.3+1.18
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		boatcontainer: BoatContainer 1.0.4
		boatiview: Boat Item View 0.0.3
		bountiful: Bountiful 2.0.1
		capes: Capes 1.2.2+1.18
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		carrier: Carrier 1.9.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.45
		clumps: Clumps 8.0.1
		coat: Coat 1.0.0-beta.15
		collective-fabric: Collective (Fabric) 3.13
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.0-1.18
		continuity: Continuity 1.0.3+1.18
		copper_golem: Copper Golem 1.2.0
		cosmetica: Cosmetica 0.3.2
		craftsaddles: Craft Saddles 1.18
		crawl: Crawl 0.10.0
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		deathlog: DeathLog 0.2.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.0
		diamond_nuggets: Diamond Nuggets 1.3
		earthtojavamobs: Earth2Java 1.7.4+1.18
		eatinganimationid: Eating Animation 1.2
		editsign: EditSign 2.2.6
		eggtab: Egg Tab 2.1.0+1.16-fabric
		emeraldextendedfabric: EmeraldExtendedFabric 1.1
		enchant_giver: Enchant Giver 1.1.0
		endgoblintraders: End Goblin Traders 1.4.2
		enhancedcelestials: Enhanced Celestials 2.0.6
		enum-extender-3000: Enum Extender 3000 1.1.0
		expandedstorage: Expanded Storage 7.3.2
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.8
		fabrishot: Fabrishot 1.6.0
		fabulousclouds: Fabulous Clouds 0.2.3
		fallingleaves: Falling Leaves 1.8.0+1.18
		fallingtree: FallingTree 2.15.2
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		flesh2leather: Flesh2Leather 1.0.2
		fpsreducer: FPS Reducer 1.25-mc1.18
		geckolib3: Geckolib 3.0.22
		gobber2: Gobber2 2.5.52
		goblintraders: Goblin Traders 1.4.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.0
		grindenchantments: Grind Enchantments 1.4.0+1.17.1
		harvest_scythes: Harvest Scythes 2.3.0
		horseinfo: Horse Info 0.4.0-1.18
		icarus: Icarus 1.9
		illuminations: Illuminations 1.10.2
		incantationem: Incantationem 1.1.2+1.18-pre1
		indium: Indium 1.0.2-alpha1+mc1.18
		inventoryhud: Inventory HUD + 3.4.2
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.0
		kirin: Kirin UI 1.10.0-beta.2
		krypton: Krypton 0.1.5
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.6-rc1
		lovely_snails: Lovely Snails 1.0.3+1.18
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-more-data: Maybe More Data 1.0.0-1.18
		medievalweapons: Medieval Weapons 1.1.7
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.18
		modmenu: Mod Menu 3.0.0
		morebannerfeatures: More Banner Features 1.1.2
		morerespawnanchors: More Respawn Anchors 1.0.3
		mores: Mores 1.2.6
		morevillagers-fabric: MoreVillagersFabric 3.0.0-SNAPSHOT
		mythicmetals: Mythic Metals 0.11.0
		mythicmetals_decorations: Mythic Metals Decorations 0.1.0
		nametagtweaks-fabric: Name Tag Tweaks (Fabric) 1.7
		netherite_nugget: Netherite Nuggets 1.4.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.6
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		notes: Notes 1.0.9
		notify: Notify 1.3.0-rc2
		npcvariety: NPC Variety 2.2.1
		obsidianequipment: Obsidian Equipment 1.18
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.18-1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		owo: oωo 0.3.8+1.18
		oxidized: Oxidized 1.5.0
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18-60-FABRIC
		pigsteel: Pigsteel Mod 1.6.6
		plushies: Plushie Mod 1.1
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		pugh_lib: Pugh Lib 1.2.11
		pugh_tools: Pugh Tools 1.1.13
		quartzelv: Quartz Elevator 2.0.0+1.18
		quilt-loading-screen: Quilt Loading Screen 2.2.1+1.17
		quitconfirm: QuitConfirm 1.4-beta.2
		ratsmischief: Rat's Mischief 1.3.3
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.18-1
		reeses-sodium-options: Reese's Sodium Options 1.2.3
		repurposed_structures: Repurposed Structures 3.1.4+1.18.0
		roughlyenoughitems: Roughly Enough Items 7.0.343
		satin: Satin 1.7.0
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		simple_backpack: SimpleBackpack 1.2.24
		simple_shelves: Simple Shelves 1.0.1
		sit: Sit 1.18-14
		snowytrees: Snowy Trees 1.0.0
		soaringstructures2: Soaring Structures 2 1.18 - 1.9.3
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		soundphysics: Sound Physics 4.0
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		sulfurpotassiummod: Sulfur & Potassium 1.1.1
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		things: Things 0.2.8+1.18
		thonkutil: ThonkUtil 1.3
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		uncraftingtable76: UncraftingTable 1.0.0
		veinmining: Vein Mining 0.0.11-1.18
		villagernames: Villager Names 2.0.2
		visuality: Visuality 0.3.3
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		vulnerableflight: Vulnerable Flight 1.0.0
		wandering_collector: Wandering Collector 1.0.3+mc1.18-rc3
		waveycapes: WaveyCapes 1.0.4
		waystones: Waystones 9.0.0
		wi_zoom: WI Zoom 1.3-MC1.18
		woodarmor: Wooden Armors (+ Stone Armor) 1.18
		wthit: wthit 4.3.1
		xaerominimap: Xaero's Minimap 21.22.3
		zombified: Zombified 1.3.0
	Launched Version: fabric-loader-0.12.8-1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.13596 Core Profile Forward-Compatible Context 20.10.44.05 27.20.11044.5003, ATI Technologies Inc.
	Window size: 925x530
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/potion-of-undying.zip (incompatible), Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, additionalbars/classic (incompatible), file/Overlay-Textures-§61.17§r (1).zip (incompatible), file/beans-e2211.zip (incompatible), lambdabettergrass/default (incompatible), file/VanillaTweaks_r135727.zip, file/VisibleOres2.2.zip (incompatible)
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Mod Menu (modmenu)
```
</details>

**Comment by jackassmc** [comment]
This is a bug in the Notify mod, please report it at https://github.com/JamCoreModding/Notify/issues.

Until there is a fix you can disable the Notify mod to prevent this crash.
