### ISSUE TITLE
Mod updates stuck; infinite loading bar.

### ISSUE THREAD

**Issue by Konglomneshued** [Prospector/ModMenu#418]
Happens 99% of the time I try to update mods.  It will just sit there and not complete the update.  It downloads an empty jar file which I have to delete or my Minecraft will crash at launch.

**Comment by Konglomneshued** [comment]
Hey I just tried updating the mod itself instead of update all and got an error message.

`Unkown error during the update process:
xyz.deathsgun.modmanager.api.http.HttpClient$InvalidStatusCodeException: Received invalid status code: 403`

**Comment by Konglomneshued** [comment]
Here is the error in my log

```
[19:00:04] [DefaultDispatcher-worker-8/INFO]: Updating Fabric API
[19:00:04] [DefaultDispatcher-worker-8/INFO]: Error while deleting C:\Users\untitled(1)\AppData\Roaming\MultiMC\instances\Magic\.minecraft\mods\fabric-api-0.50.0+1.18.2.jar trying on restart again
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: xyz.deathsgun.modmanager.api.http.HttpClient$InvalidStatusCodeException: Received invalid status code: 403
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.api.http.HttpClient.download(HttpClient.kt:48)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.installVersion(UpdateManager.kt:302)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.updateMod(UpdateManager.kt:340)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.updateMod$default(UpdateManager.kt:329)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen.updateMod(ModProgressScreen.kt:137)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen.access$updateMod(ModProgressScreen.kt:39)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen$init$2.invokeSuspend(ModProgressScreen.kt:69)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[19:00:08] [DefaultDispatcher-worker-8/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[19:00:08] [DefaultDispatcher-worker-8/ERROR]: modmanager.error.unknown.update
```

**Comment by haykam821** [comment]
This is an issue with Mod Manager and not Mod Menu.

**Comment by jackassmc** [comment]
> This is an issue with Mod Manager and not Mod Menu.

Please report it at [ModManagerMC/ModManager](https://github.com/ModManagerMC/ModManager).
