### ISSUE TITLE
Crash on 1.19.1-rc1

### ISSUE THREAD

**Issue by PencilVoid** [Prospector/ModMenu#461]
When loaded win 1.19.1-rc1, with version 0.14.8 of the Fabric modloader and version 0.56.3 of the Fabric API, the game will crash upon clicking the "Mods" button, be it ingame or in the main menu. Tested with many mods loaded and with nothing but Mod Menu and the Fabric API loaded; crash occured in both scenarios.

Crash log, with only Mod Menu and the Fabric API loaded:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 26/06/2022, 10:43
Description: Rendering screen

java.lang.NoSuchMethodError: 'void com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.method_25311(net.minecraft.class_4587, int, int, int, int, float)'
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.method_25394(DescriptionListWidget.java:199)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:275)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1164)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.method_25394(DescriptionListWidget.java:199)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:275)

-- Screen render details --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
	Mouse location: Scaled: (262, 218). Absolute: (524.000000, 436.000000)
	Screen size: Scaled: (480, 270). Absolute: (960, 540). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1164)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks.zip, Fabric Mods, connected-planks.zip, connectibles-e1140.zip, fixed-smooth-stone-e2130.zip, better-farmland-e1870.zip, fungus-s-blocks-e3420.zip, Sully'sPeeves.zip, Vanilla+Collections_1.18-1.1.3.zip, Glazed Light Gray Terracotta Fix.zip, semiirontorches-v1.zip, moss.zip, Better+Dripleaf+Stems+v1.0.zip, Dripleaf_Umbrella_v1.1.zip, Desert_Bloom-v1.0.2.zip, smooth-redstone.zip, BetterCarpets.zip, wool-remade.zip, distinct_ores, Improved Buttons.zip, §9Rails-Reimagined§8-[v1.1].zip, §4§lVisual§0-§c§lTarget§0-§4§lLevels§0-§7§o1.3§0-§8.zip, §6Doors-Reimagined§8-[v1.1].zip, §bCraftingTable-Reimagined§8-[v1].zip, colorful-pumpkins-watermelons.zip, flamier-fire-e1760.zip, AM_variatedgrasses_v1.0.1_MC18.zip, loooong-fences.zip, masteremerald.zip, prettier-glowstone-e3640.zip, Cloud's+Clearer+Spawners+[1.18+16x]+V2.1.0.zip, better-command-blocks-e2220.zip, Border Powder Snow.zip, rope-ladders.zip, §6Furnaces-Reimagined§8-[v1].zip, Macarons!, New+Chests+[Spruce+Trapped].zip, prismarine-extended.zip, fully-grown-nether-vines-bud.zip, age-25-cave-vines.zip, lotus-flower-1566028340.zip, creeping-ivy.zip, Flowering Crops, henrys-better-sugar-cane.zip, §2§lVisual§0-§a§lLeaf§0-§2§lDecay§0-§7§o1.3§0-§8.zip, 3d-sweet-berry-bush-1-16.zip, §a3D Saplings, Kubban's Saplings, §cFrag§erant §bFlow§ders, colorful-spore-blossoms.zip, Authentic+Shadows_1.17+.zip, updated-minecarts-e520.zip, cat-creeper-1-18-e1520.zip, §ePigs+Reimagined§8-[v1].zip, §eArmorstands-Reimagined§8-[v1.2].zip, §6Hatson's+Foxes+v2.0+-+1.16.zip, catpeople-e1490.zip, §aSheeps-Reimagined§8-[v1].zip, creepermaxc123-s-better-piglins.zip, moth-endermen-1-18-e1570.zip, The Doggos v0.3.zip, §7New Vexes §c- Requires Opti§efine, §bNew Allays, shulker.zip, Goat variations, Slim armor, Social Armor, Jog's-Spawn-Eggs-1_19.zip, illegal-blocks.zip, Trance Music over 11 v.1.5.zip, full bundles.zip, InventoryGlassPane3D-1.18.zip, iso-barrier-zip.zip, Better Effective Mod Aspect, echo_shard_reimagine, itemredesigns-1.3-1.16.zip, bedrock-water-e2380.zip, 3d-breaking.zip, 3d breaking particles.zip, diamonds in the sky.zip, Multiolour_Fade_Outlines-v1.zip, Beehive to Apiary.zip, PVGUI-NEO, vhs-pumpkinblur.zip, Invisible Item Frame Pack_1.18.1-1.0.zip, Mizunos 16 Craft JE CIT_1.18.1-1.0.zip, itemboundrebound-e3390.zip, Lithos-Font+v12+for+1.18x.zip, segoeui, nihhiu_music, custom splash texts
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2329)
	at net.minecraft.class_310.method_1514(class_310.java:774)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.1 Release Candidate 1
	Minecraft Version ID: 1.19.1-rc1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1511368560 bytes (1441 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Pentium(R) CPU G3250 @ 3.20GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0402
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4624
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 8377.32
	Virtual memory used (MB): 6401.95
	Swap memory total (MB): 4409.14
	Swap memory used (MB): 660.47
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -Xms2G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=25 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.56.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+82552130a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.24+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.2+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.9+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.6+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.4+db8596f1a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.1-rc.1
		modmenu: Mod Menu 4.0.0
	Launched Version: fabric-loader-0.14.8-1.19.1-rc1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics GL version 3.2.0 - Build 20.19.15.4624, Intel
	Window size: 960x540
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/VanillaTweaks.zip, Fabric Mods, file/connected-planks.zip (incompatible), file/connectibles-e1140.zip (incompatible), file/fixed-smooth-stone-e2130.zip (incompatible), file/better-farmland-e1870.zip (incompatible), file/fungus-s-blocks-e3420.zip (incompatible), file/Sully'sPeeves.zip (incompatible), file/Vanilla+Collections_1.18-1.1.3.zip (incompatible), file/Glazed Light Gray Terracotta Fix.zip (incompatible), file/semiirontorches-v1.zip (incompatible), file/moss.zip (incompatible), file/Better+Dripleaf+Stems+v1.0.zip (incompatible), file/Dripleaf_Umbrella_v1.1.zip (incompatible), file/Desert_Bloom-v1.0.2.zip (incompatible), file/smooth-redstone.zip (incompatible), file/BetterCarpets.zip (incompatible), file/wool-remade.zip (incompatible), file/distinct_ores (incompatible), file/Improved Buttons.zip (incompatible), file/§9Rails-Reimagined§8-[v1.1].zip (incompatible), file/§4§lVisual§0-§c§lTarget§0-§4§lLevels§0-§7§o1.3§0-§8.zip, file/§6Doors-Reimagined§8-[v1.1].zip (incompatible), file/§bCraftingTable-Reimagined§8-[v1].zip (incompatible), file/colorful-pumpkins-watermelons.zip (incompatible), file/flamier-fire-e1760.zip (incompatible), file/AM_variatedgrasses_v1.0.1_MC18.zip (incompatible), file/loooong-fences.zip (incompatible), file/masteremerald.zip (incompatible), file/prettier-glowstone-e3640.zip (incompatible), file/Cloud's+Clearer+Spawners+[1.18+16x]+V2.1.0.zip (incompatible), file/better-command-blocks-e2220.zip (incompatible), file/Border Powder Snow.zip (incompatible), file/rope-ladders.zip (incompatible), file/§6Furnaces-Reimagined§8-[v1].zip (incompatible), file/Macarons! (incompatible), file/New+Chests+[Spruce+Trapped].zip (incompatible), file/prismarine-extended.zip (incompatible), file/fully-grown-nether-vines-bud.zip (incompatible), file/age-25-cave-vines.zip (incompatible), file/lotus-flower-1566028340.zip (incompatible), file/creeping-ivy.zip (incompatible), file/Flowering Crops (incompatible), file/henrys-better-sugar-cane.zip (incompatible), file/§2§lVisual§0-§a§lLeaf§0-§2§lDecay§0-§7§o1.3§0-§8.zip, file/3d-sweet-berry-bush-1-16.zip (incompatible), file/§a3D Saplings (incompatible), file/Kubban's Saplings (incompatible), file/§cFrag§erant §bFlow§ders, file/colorful-spore-blossoms.zip (incompatible), file/Authentic+Shadows_1.17+.zip (incompatible), file/updated-minecarts-e520.zip (incompatible), file/cat-creeper-1-18-e1520.zip (incompatible), file/§ePigs+Reimagined§8-[v1].zip (incompatible), file/§eArmorstands-Reimagined§8-[v1.2].zip (incompatible), file/§6Hatson's+Foxes+v2.0+-+1.16.zip (incompatible), file/catpeople-e1490.zip (incompatible), file/§aSheeps-Reimagined§8-[v1].zip (incompatible), file/creepermaxc123-s-better-piglins.zip (incompatible), file/moth-endermen-1-18-e1570.zip (incompatible), file/The Doggos v0.3.zip (incompatible), file/§7New Vexes §c- Requires Opti§efine (incompatible), file/§bNew Allays, file/shulker.zip (incompatible), file/Goat variations (incompatible), file/Slim armor (incompatible), file/Social Armor (incompatible), file/Jog's-Spawn-Eggs-1_19.zip, file/illegal-blocks.zip (incompatible), file/Trance Music over 11 v.1.5.zip (incompatible), file/full bundles.zip (incompatible), file/InventoryGlassPane3D-1.18.zip (incompatible), file/iso-barrier-zip.zip (incompatible), file/Better Effective Mod Aspect (incompatible), file/echo_shard_reimagine, file/itemredesigns-1.3-1.16.zip (incompatible), file/bedrock-water-e2380.zip (incompatible), file/3d-breaking.zip (incompatible), file/3d breaking particles.zip (incompatible), file/diamonds in the sky.zip (incompatible), file/Multiolour_Fade_Outlines-v1.zip (incompatible), file/Beehive to Apiary.zip (incompatible), file/PVGUI-NEO (incompatible), file/vhs-pumpkinblur.zip (incompatible), file/Invisible Item Frame Pack_1.18.1-1.0.zip (incompatible), file/Mizunos 16 Craft JE CIT_1.18.1-1.0.zip (incompatible), file/itemboundrebound-e3390.zip (incompatible), file/Lithos-Font+v12+for+1.18x.zip (incompatible), file/segoeui (incompatible), file/nihhiu_music (incompatible), file/custom splash texts (incompatible)
	Current Language: English (United Kingdom)
	CPU: 2x Intel(R) Pentium(R) CPU G3250 @ 3.20GHz
```

**Comment by jackassmc** [comment]
Fixed in [v4.0.1](https://modrinth.com/mod/modmenu/version/4.0.1). Thanks for reporting!
