### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MetsukiMio** [Prospector/ModMenu#518]
![image](https://user-images.githubusercontent.com/83895170/210958956-4dcffdfe-686d-4ddb-b7ad-559aaae04b7e.png)
I am making a mod that used your mod api.But It cannot work in MC 1.19.3.

```
java.lang.IllegalAccessError: class com.terraformersmc.modmenu.event.ModMenuEventHandler tried to access private field net.minecraft.client.gui.widget.ClickableWidget.y (com.terraformersmc.modmenu.event.ModMenuEventHandler and net.minecraft.client.gui.widget.ClickableWidget are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @71423665)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.shiftButtons(ModMenuEventHandler.java:146)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterTitleScreenInit(ModMenuEventHandler.java:61)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterScreenInit(ModMenuEventHandler.java:45)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101)
	at net.minecraft.client.gui.screen.Screen.handler$zde000$afterInitScreen(Screen.java:1345)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:387)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1049)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:673)
	at net.minecraft.client.main.Main.main(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by Prospector** [comment]
What version of Mod Menu are you using?

**Comment by twisted-nematic57** [comment]
Same issue here. I tried with 5.0.1 and 5.0.2, same errors. A list of my other mods is attached.

The error still occurs when mod menu is the only active mod.

![image](https://user-images.githubusercontent.com/70416002/216783380-5a725b96-32bd-48ed-b9de-58db3e21e7c1.png)

**Comment by HackerDaGreat57** [comment]
Reinstalling Fabric made it work for me. Issue solved.

**Comment by HackerDaGreat57** [comment]
I saw that

**Comment by haykam821** [comment]
@HackerDaGreat57 Could you post your own game log with the minimal reproduction environment? Only the latest Fabric loader and Mod Menu versions should be installed for Minecraft 1.19.3.

**Comment by MetsukiMio** [comment]
I am using ModMenu version 5.0.2

**Comment by MetsukiMio** [comment]
this bug didn't occured in 1.19.2, because field "net.minecraft.client.gui.widget.ClickableWidget.y" has "public" modifier in 1.19.2, but this field changed to "private" modifier in 1.19.3 and been replaced by "getY" method.

**Comment by Prospector** [comment]
Can you still reproduce with the latest version?
