### ISSUE TITLE
Clicking the Mods button in the main menu crashes the game

### ISSUE THREAD

**Issue by ghost** [Prospector/ModMenu#592]
It's my first time to try fabric and modmenu.

After starting up the game, when I click 'Mods' on the main menu, the game exits and reports this error:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-04-14 13:18:43
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'void com.terraformersmc.modmenu.gui.ModsScreen.method_20085(net.minecraft.class_364)'
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:249)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:308)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:249)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:308)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Mac OS X (x86_64) version 12.6.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 284571856 bytes (271 MiB) / 905969664 bytes (864 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 70 Stepping 1
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Pro
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0d26
	Graphics card #0 versionInfo: Revision ID: 0x0008
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 27648.00
	Virtual memory used (MB): 19769.47
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 9814.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.42
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.42
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.42
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.42
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.42
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.42
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.42
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.42
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.42
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.42
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.42
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.42
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.42
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.42
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.42
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.42
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.42
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.42
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.42
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.42
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		fabric-api: Fabric API 0.77.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.53+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.6+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.0+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.40+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.7+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.3+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.19+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		fastload: Fast Load 3.3.1
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.3.1
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.3.1
			fastload-1194-compat: Fastload 1.19.4 Compat 3.3.1
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.1
		ferritecore: FerriteCore 5.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 5.0.2
		nochatreports: No Chat Reports 1.19.4-v2.1.1
		smoothboot: Smooth Boot 1.19.4-1.7.0
		starlight: Starlight 1.1.1+fabric.ae22326
		vmp: Very Many Players 0.2.0+beta.7.70
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel Iris Pro OpenGL Engine GL version 4.1 INTEL-18.8.5, Intel Inc.
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
```

**Comment by Prospector** [comment]
You're using the wrong version of Mod Menu. You're using Mod Menu for Minecraft 1.19.3 on 1.19.4

You can get the latest here: https://modrinth.com/mod/modmenu/version/latest?g=1.19.4

**Comment by ghost** [comment]
Thank you, you're right and that fixed it

**Comment by haykam821** [comment]
Duplicate of #580
