### ISSUE TITLE
[Nocrash] Check for Modrinth Update error

### ISSUE THREAD

**Issue by Tursiops-G** [Prospector/ModMenu#594]
Modrinth Update check code may need a little TLC...?

```
[12:34:21] [Worker-Main-1/ERROR]: Caught exception in thread Thread[Worker-Main-1,5,main]
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$4(ModrinthUtil.java:86) ~[modmenu-6.2.0.jar:?]
	at java.util.Map.forEach(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$5(ModrinthUtil.java:79) ~[modmenu-6.2.0.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```

**Comment by FunkyNico** [comment]
I can confirm i have the same "ERROR" on console, logs here:

```
[12:21:05] [Worker-Main-1/ERROR]: Caught exception in thread Thread[Worker-Main-1,5,main]
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$4(ModrinthUtil.java:86) ~[modmenu-6.2.3.jar:?]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$5(ModrinthUtil.java:79) ~[modmenu-6.2.3.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by haykam821** [comment]
Is this issue still present in [version 7.1.0](https://github.com/TerraformersMC/ModMenu/releases/tag/v7.1.0)?

**Comment by FunkyNico** [comment]
> Is this issue still present in [version 7.1.0](https://github.com/TerraformersMC/ModMenu/releases/tag/v7.1.0)?

I tested 7.1.0 on Minecraft 1.20.1 with Quilt and didn't have the issue. But it's still present on 1.19.4 with version 6.2.3.

**Comment by haykam821** [comment]
The fix hasn't been backported to earlier Minecraft versions, but I'll close the issue as it has been fixed on the latest Minecraft version.
