### ISSUE TITLE
Crash when pressing F3 + Esc

### ISSUE THREAD

**Issue by UpcraftLP** [Prospector/ModMenu#61]
WHen pressing `F3 + Esc` (pause the game without visible screen in singleplayer) the game crasehs due to ModMenu's mixin trying to access index 5 of an empty array list.

I encountered the issue in AOF first, and was able to reproduce it in my dev workspace:
```
java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:665) ~[?:1.8.0_212]
	at java.util.ArrayList.add(ArrayList.java:477) ~[?:1.8.0_212]
	at net.minecraft.client.gui.screen.GameMenuScreen.addButton(GameMenuScreen.java:534) ~[minecraft-1.14.4-mapped-net.fabricmc.yarn-5.jar:?]
	at net.minecraft.client.gui.screen.GameMenuScreen.handler$drawMenuButton$zep001(GameMenuScreen.java:527) ~[minecraft-1.14.4-mapped-net.fabricmc.yarn-5.jar:?]
```

which leads to this line in the mixin output:
```java
    @MixinMerged(
        mixin = "io.github.prospector.modmenu.mixin.PauseMenuScreenMixin",
        priority = 1000,
        sessionId = "e4704896-c392-449d-8fc2-5270d7798be2"
    )
    public void handler$drawMenuButton$zep001(CallbackInfo info) {
        int i = FabricLoader.getInstance().getAllMods().size();
        this.addButton(new ModMenuButtonWidget(this.width / 2 - 102, this.height / 4 + 8 + 72, 204, 20, (ModMenu.noFabric ? "Mods" : I18n.translate("modmenu.title", new Object[0])) + " " + (ModMenu.noFabric ? "(" + i + " Loaded)" : I18n.translate("modmenu.loaded", new Object[]{i})), this), 5);
    }
```
(uses index 5).

Can be fixed by moving the injection into `initWidgets()` instead of `init()`.

**Comment by Prospector** [comment]
Ah, nice catch
