### ISSUE TITLE
When I click on the mod menu button, minecraft crashes.

### ISSUE THREAD

**Issue by qumii2** [Prospector/ModMenu#614]
When I click on the mod menu button, minecraft crashes.
Description: mouseClicked event handler
I went through different versions, removed mods related to the menu - nothing.

**Comment by haykam821** [comment]
Could you post your client log?

**Comment by qumii2** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-06-22 23:42:06
Description: mouseClicked event handler

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_350 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:128)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:14)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:308)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 47 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector modifyChildrenCall(Lnet/minecraft/class_350;)Ljava/util/List; in yacl.mixins.json:AbstractSelectionListMixin from mod yet_another_config_lib failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap yet-another-config-lib-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 50 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:128)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:14)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:308)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
Mixins in Stacktrace:
	net.minecraft.class_437:
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.Mixin_PassEventsExt (mixins.jgui.json)
		com.misterpemodder.shulkerboxtooltip.mixin.client.ScreenMixin (shulkerboxtooltip-common.mixins.json)
		com.replaymod.core.mixin.GuiScreenAccessor (mixins.core.replaymod.json)
		net.blay09.mods.balm.mixin.ScreenAccessor (balm.mixins.json)
		com.tterrag.blur.mixin.MixinScreen (mixins.blur.json)
		com.anthonyhilyard.iceberg.mixin.ScreenMixin (iceberg.mixins.json)
		fi.dy.masa.malilib.mixin.MixinScreen (mixins.malilib.json)
		com.anthonyhilyard.legendarytooltips.mixin.ScreenMixin (legendarytooltips.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.ScreenAccessor (mixins.libgui.json)
		net.fabricmc.fabric.mixin.screen.ScreenMixin (fabric-screen-api-v1.mixins.json)
		gg.essential.mixins.transformers.client.gui.GuiScreenAccessor (mixins.essential.json)
		dev.architectury.mixin.fabric.client.MixinScreen (architectury.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinScreen (konkrete.mixin.json)
		gg.essential.mixins.transformers.client.gui.MixinGuiScreen (mixins.essential.json)
		me.shedaniel.rei.mixin.fabric.MixinScreen (rei.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinScreen (mixins.jgui.json)
		net.fabricmc.fabric.mixin.screen.ScreenAccessor (fabric-screen-api-v1.mixins.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (tcdcommons.client.mixin.events.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (zoomify.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		gg.essential.mixins.transformers.feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo (mixins.essential.json)
		io.github.darkkronicle.advancedchatcore.mixin.MixinMinecraftClient (advancedchatcore.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		com.ishland.vmp.mixins.timesource.MixinMinecraftClient (vmp.mixins.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
		de.keksuccino.auudio.mixin.client.MixinMinecraft (auudio.mixin.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		me.jellysquid.mods.sodium.mixin.workarounds.issue1486.MixinMinecraftClient (sodium.mixins.json)
		gg.essential.mixins.transformers.client.gui.Mixin_RecalculateMenuScale (mixins.essential.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (mixins.jgui.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		de.johni0702.minecraft.bobby.mixin.MinecraftClientMixin (bobby.mixins.json)
		com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
		io.github.darkkronicle.darkkore.mixins.MixinMinecraftClient (darkkore.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		de.siphalor.amecs.impl.mixin.MixinMinecraftClient (amecsapi.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (forgeconfigapiport.common.mixins.json)
		gg.essential.mixins.transformers.client.MixinMinecraft (mixins.essential.json)
		me.hypherionmc.simplerpc.mixin.ScreenEventsMixin (simplerpc.mixins.json)
		io.github.sjouwer.gammautils.mixin.MixinMinecraftClient (gammautils.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
		de.guntram.mcmod.clickthrough.mixins.ItemUseMixin (mixins.clickthrough.json)
		io.github.darkkronicle.advancedchathud.mixin.MixinMinecraftClient (advancedchathud.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		gg.essential.mixins.transformers.client.gui.Mixin_FixKeybindUnpressedInEmoteWheel (mixins.essential.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl3.mixins.json)
		com.replaymod.render.mixin.Mixin_SuppressFramebufferResizeDuringRender (mixins.render.replaymod.json)
	net.minecraft.class_4185:
		io.github.thecsdev.tcdcommons.client.mixin.hooks.MixinButtonWidget (tcdcommons.client.mixin.hooks.json)
	net.minecraft.class_339:
		io.github.darkkronicle.darkkore.mixins.MixinClickableWidget (darkkore.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.IMixinAbstractWidget (konkrete.mixin.json)
		com.replaymod.core.mixin.AbstractButtonWidgetAccessor (mixins.core.replaymod.json)
	net.minecraft.class_4069:
		dev.isxander.yacl3.mixin.ContainerEventHandlerMixin (yacl3.mixins.json)
	net.minecraft.class_442:
		net.coderbot.iris.mixin.MixinTitleScreen (mixins.iris.json)
		me.flashyreese.mods.sodiumextra.mixin.compat.MixinTitleScreen (sodium-extra.mixins.json)
		com.terraformersmc.modmenu.mixin.MixinTitleScreen (mixins.modmenu.json)
		de.guntram.mcmod.fabrictools.mixins.MixinMainMenuScreen (mixins.de-guntram-mcmod-fabrictools.json)
		gg.essential.mixins.transformers.client.gui.MixinGuiMainMenu (mixins.essential.json)
		com.replaymod.replay.mixin.Mixin_MoveRealmsButton (mixins.replay.replaymod.json)
	net.minecraft.class_312:
		de.siphalor.amecs.impl.mixin.MixinMouse (amecsapi.mixins.json)
		gg.essential.mixins.transformers.client.MouseHelperAccessor (mixins.essential.json)
		de.keksuccino.konkrete.mixin.mixins.client.IMixinMouseHandler (konkrete.mixin.json)
		ru.feytox.spwallet.mixin.MouseMixin (SPwallet.mixins.json)
		com.replaymod.core.mixin.MixinMouse (mixins.core.replaymod.json)
		dev.architectury.mixin.fabric.client.MixinMouseHandler (architectury.mixins.json)
		gg.essential.mixins.transformers.events.Mixin_GuiMouseDraggedEvent (mixins.essential.json)
		net.fabricmc.fabric.mixin.screen.MouseMixin (fabric-screen-api-v1.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMouseHandler (konkrete.mixin.json)
		io.github.darkkronicle.darkkore.mixins.MixinMouse (darkkore.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMouseListener (mixins.jgui.json)
		gg.essential.mixins.transformers.events.Mixin_GuiClickEvent (mixins.essential.json)
		net.blay09.mods.balm.mixin.MouseHandlerAccessor (balm.mixins.json)
		gg.essential.mixins.transformers.events.Mixin_GuiClickEvent_Priority (mixins.essential.json)
		gg.essential.mixins.transformers.feature.chat.Mixin_ChatPeekScrolling (mixins.essential.json)
		su.plo.voice.client.mixin.MixinMouseHandler (plasmovoice.mixins.json)
		dev.isxander.zoomify.mixins.zoom.MouseMixin (zoomify.mixins.json)
		yalter.mousetweaks.fabric.mixin.MixinMouseHandler (mousetweaks-fabric.mixins.json)
		net.blay09.mods.balm.mixin.MouseHandlerMixin (balm.mixins.json)
		team.creative.creativecore.mixin.MouseHandlerAccessor (creativecore.mixins.json)
		gg.essential.mixins.transformers.events.Mixin_GuiMouseReleaseEvent (mixins.essential.json)
		gg.essential.mixins.transformers.events.Mixin_MouseScrollEvent (mixins.essential.json)
		fi.dy.masa.malilib.mixin.MixinMouse (mixins.malilib.json)
		com.replaymod.recording.mixin.MixinMouseHelper (mixins.recording.replaymod.json)
	net.minecraft.class_1255:
		dynamicfps.mixin.ThreadExecutorMixin (dynamicfps.mixins.json)
	com.mojang.blaze3d.systems.RenderSystem:
		net.coderbot.iris.mixin.MixinGlStateManager (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.workarounds.MixinRenderSystem (sodium.mixins.json)
		gg.essential.mixins.transformers.client.Mixin_SuppressScreenshotBufferFlip (mixins.essential.json)
		net.coderbot.iris.mixin.statelisteners.MixinRenderSystem (mixins.iris.json)
		com.replaymod.replay.mixin.MixinTileEntityEndPortalRenderer (mixins.replay.replaymod.json)
		net.coderbot.iris.mixin.MixinRenderSystem (mixins.iris.json)

p.s.: Sorry, I'm inexperienced

**Comment by TheSpiderDungeon** [comment]
Since it's been like a month with no reply, I assume the developer doesn't know what caused the crash.

**Comment by LostLuma** [comment]
https://github.com/isXander/YetAnotherConfigLib/issues/84
