### ISSUE TITLE
Unable to use Modmenu 7.1.0 for 1.20.1 in Dev environment

### ISSUE THREAD

**Issue by Dev0Louis** [Prospector/ModMenu#617]
I bumped mod menu and my version, but when I use modmenu 7.1.0 it does not work and the game crashes with 

```java
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.text.MutableText net.minecraft.text.Text.method_43471(java.lang.String)'
	at com.terraformersmc.modmenu.config.option.BooleanConfigOption.<init>(BooleanConfigOption.java:19)
	at com.terraformersmc.modmenu.config.option.BooleanConfigOption.<init>(BooleanConfigOption.java:24)
	at com.terraformersmc.modmenu.config.ModMenuConfig.<clinit>(ModMenuConfig.java:20)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:140)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1169)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1148)```

**Comment by gniftygnome** [comment]
Are you using ModMenu in 1.20.1 or just 1.20?

**Comment by Dev0Louis** [comment]
> Are you using ModMenu in 1.20.1 or just 1.20?

I use 1.20.1

**Comment by generrosity** [comment]
I think I got a similar thing, as I was testing a pack idea in CurseForge app but I think you might have 'fixed' it recently by removing it due to curse being ... cursed. 2.0.17 is hardly current - should be v7+! 😅

![image](https://github.com/TerraformersMC/ModMenu/assets/12838061/540ca13d-bf2b-44ee-9808-14faea1a61e6)
