### ISSUE TITLE
Crash when opening mod menu (click mods button)

### ISSUE THREAD

**Issue by wolfgangvc** [Prospector/ModMenu#64]
Crashes when pressing the mod menu button.

Clicked the button, text appears saying saving world, then this crash happens.

```
MultiMC version: 0.6.7-1375


Minecraft folder is:
C:/Users/--------/Downloads/Games/Minecraft/MultiMC/instances/multimc/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_211, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/instances/multimc/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/fabric-loader/0.4.8+build.159/fabric-loader-0.4.8+build.159.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/yarn/1.14.4+build.11/yarn-1.14.4+build.11.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/tiny-remapper/0.1.0.33/tiny-remapper-0.1.0.33.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] cmdkeybind-1.2.1
  [✔️] fabric-api-0.3.1+build.208
  [✔️] fabricmod_VoxelMap-1.9.13_for_1.14.4
  [✔️] LightOverlay-3.4
  [✔️] litematica-fabric-1.14.4-0.0.0-dev.20190720.191654
  [✔️] malilib-fabric-1.14.4-0.10.0-dev.20
  [📁] mamiyaotaru (folder)
  [✔️] modmenu-1.7.9-unstable.19w34a+build.1
  [✔️] mousewheelie-1.2.13+1.14.4
  [✔️] orderly-1.1.1+build.16

Params:
  --username  --version MultiMC5 --gameDir C:/Users/--------/Downloads/Games/Minecraft/MultiMC/instances/multimc/.minecraft --assetsDir C:/Users/--------/Downloads/Games/Minecraft/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 10616


Using onesix launcher.

[19:23:57] [main/INFO]: Loading for game Minecraft 1.14.4
[19:24:00] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-keybindings-v0: used 0.1.1+7dfef87c42, also found 0.1.1+7dfef87c55
 - Conflicting versions found for fabric-api-base: used 0.1.0+5914746355, also found 0.1.0+b494ebeb42
 - Conflicting versions found for fabric-tag-extensions-v0: used 0.1.1+b494ebeb42, also found 0.1.1+c189dc5c55
 - Conflicting versions found for fabric-mining-levels-v0: used 0.1.0+59147463, also found 0.1.0+ab421b9c42
[19:24:00] [main/WARN]: Mod `lightoverlay` (3.4) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[19:24:00] [main/WARN]: Mod `voxelmap` (1.9.13) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[19:24:00] [main/WARN]: Mod `tweed` (2.2.2) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[19:24:00] [main/WARN]: Mod `cloth` (0.3.1+build.23) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[19:24:00] [main/INFO]: [FabricLoader] Loading 39 mods: fabric-renderer-api-v1@0.1.1+9b03381f42, fabric-networking-blockentity-v0@0.1.1+b494ebeb42, fabric-keybindings-v0@0.1.1+7dfef87c42, modmenu@1.7.9-unstable.19w34a+build.1, fabricloader@0.4.8+build.159, cmdkeybind@1.2.1, fabric-renderer-indigo@0.1.10+f0fe03ff42, fabric-containers-v0@0.1.2+b494ebeb42, fabric-biomes-v1@0.1.0+896c7fbb42, fabric-crash-report-info-v1@0.1.1+9f55aa7042, fabric-events-interaction-v0@0.1.1+9f55aa7042, orderly@1.1.1+build.16, fabric-api-base@0.1.0+5914746355, fabric-rendering-v0@0.1.1+6dad974e42, mousewheelie@1.2.13+1.14.4, cloth-config2@1.0.0, fabric-rendering-data-attachment-v1@0.1.0+b494ebeb42, fabric-resource-loader-v0@0.1.2+232e294c42, fabric-textures-v0@0.1.4+b494ebeb42, malilib@0.10.0-dev.20, fabric-content-registries-v0@0.1.1+b494ebeb42, fabric-tag-extensions-v0@0.1.1+b494ebeb42, blue_endless_jankson@+, fabric-rendering-fluids-v1@0.1.1+39442fc242, fabric-commands-v0@0.1.1+b494ebeb42, litematica@0.0.0-dev.20190720.191654, fabric-registry-sync-v0@0.2.2+9b03381f42, lightoverlay@3.4, fabric-mining-levels-v0@0.1.0+59147463, voxelmap@1.9.13, fabric-events-lifecycle-v0@0.1.1+eff46b3d42, fabric-loot-tables-v1@0.1.0+b494ebeb42, fabric@0.3.1+build.208, fabric-models-v0@0.1.0+5914746342, fabric-item-groups-v0@0.1.0+1e69a0a542, fabric-object-builders-v0@0.1.1+9b03381f42, fabric-networking-v0@0.1.3+9f55aa7042, tweed@2.2.2, cloth@0.3.1+build.23
[19:24:00] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[19:24:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/--------/Downloads/Games/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[19:24:01] [main/INFO]: Compatibility level set to JAVA_8
[19:24:02] [main/INFO]: Setting user: ---------
[19:24:06] [main/INFO]: [Indigo] Registering Indigo renderer!
[19:24:07] [main/INFO]: Reloaded configs for mousewheelie
[19:24:07] [main/WARN]: Skipping bad option: lastServer:
[19:24:07] [main/INFO]: LWJGL Version: 3.2.2 build 10
[19:24:13] [main/INFO]: Narrator library for x64 successfully loaded
AL lib: (EE) UpdateDeviceParams: Failed to set Stereo, got 7.1 Surround instead
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
[19:24:24] [main/INFO]: OpenAL initialized.
[19:24:24] [main/INFO]: Sound engine started
[19:24:24] [main/INFO]: Created: 1024x512 textures-atlas
[19:24:24] [main/INFO]: Created: 256x256 textures/particle-atlas
[19:24:24] [main/INFO]: Created: 256x256 textures/painting-atlas
[19:24:24] [main/INFO]: Created: 256x128 textures/mob_effect-atlas
[19:24:24] [main/INFO]: Reloaded configs for mousewheelie
[19:24:25] [main/INFO]: [STDOUT]: CATEGORY ORDER IS 9
[19:24:25] [main/INFO]: Created: 256x256 waypoints-atlas
[19:24:25] [main/INFO]: Created: 256x128 chooser-atlas
[19:24:26] [main/INFO]: Created: 512x256 mobs-atlas
[19:24:26] [main/INFO]: Created: 64x64 pings-atlas
[19:24:32] [main/INFO]: Connecting to ------, 25565
[19:24:34] [main/INFO]: [CHAT] --------- joined the game
[19:24:36] [main/WARN]: Received passengers for unknown entity
[19:24:36] [main/INFO]: Loaded 513 advancements
[19:24:36] [main/INFO]: [CHAT] Welcome, ---------!
[19:24:36] [main/INFO]: [CHAT] Type /help for a list of commands.
[19:24:36] [main/INFO]: [CHAT] Type /list to see who else is online.
[19:24:36] [main/INFO]: [CHAT] Players online: 3 - World time: 1:53 PM
[19:24:36] [main/INFO]: [CHAT] You have no new mail.
[19:24:42] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
    at net.minecraft.class_757.method_3192(class_757.java:695) ~[intermediary-minecraft-1.14.4-client.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:954) ~[intermediary-minecraft-1.14.4-client.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:410) [intermediary-minecraft-1.14.4-client.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-minecraft-1.14.4-client.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.159.jar:?]
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.159.jar:?]
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.159.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/mojang/blaze3d/systems/RenderSystem
    at io.github.prospector.modmenu.gui.ModListScreen.overlayBackground(ModListScreen.java:294) ~[modmenu-1.7.9-unstable.19w34a+build.1.jar:?]
    at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:231) ~[modmenu-1.7.9-unstable.19w34a+build.1.jar:?]
    at net.minecraft.class_757.method_3192(class_757.java:686) ~[intermediary-minecraft-1.14.4-client.jar:?]
    ... 18 more
Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.systems.RenderSystem
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160) ~[fabric-loader-0.4.8+build.159.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
    at io.github.prospector.modmenu.gui.ModListScreen.overlayBackground(ModListScreen.java:294) ~[modmenu-1.7.9-unstable.19w34a+build.1.jar:?]
    at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:231) ~[modmenu-1.7.9-unstable.19w34a+build.1.jar:?]
    at net.minecraft.class_757.method_3192(class_757.java:686) ~[intermediary-minecraft-1.14.4-client.jar:?]
    ... 18 more
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 28/08/19 19:24
Description: Rendering screen

java.lang.NoClassDefFoundError: com/mojang/blaze3d/systems/RenderSystem
    at io.github.prospector.modmenu.gui.ModListScreen.overlayBackground(ModListScreen.java:294)
    at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:231)
    at net.minecraft.class_757.method_3192(class_757.java:686)
    at net.minecraft.class_310.method_1523(class_310.java:954)
    at net.minecraft.class_310.method_1514(class_310.java:410)
    at net.minecraft.client.main.Main.main(Main.java:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.systems.RenderSystem
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at io.github.prospector.modmenu.gui.ModListScreen.overlayBackground(ModListScreen.java:294)
    at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:231)

-- Screen render details --
Details:
    Screen name: io.github.prospector.modmenu.gui.ModListScreen
    Mouse location: Scaled: (485, 204). Absolute: (970.000000, 408.000000)
    Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000

-- Affected level --
Details:
    All players: 2 total; [class_746['---------'/60695, l='MpServer', x=206.70, y=7.00, z=-100.70], class_745['SoulRetriever'/59265, l='MpServer', x=206.70, y=7.00, z=-99.30]]
    Chunk stats: Client Chunk Cache: 729, 471
    Level dimension: minecraft:overworld
    Level name: MpServer
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: {}
    Level spawn location: World: (105,74,-74), Chunk: (at 9,4,6 in 6,-5; contains blocks 96,0,-80 to 111,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 22532 game time, 12224046 day time
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Server brand: Paper
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.class_638.method_8538(class_638.java:421)
    at net.minecraft.class_310.method_1587(class_310.java:1923)
    at net.minecraft.class_310.method_1514(class_310.java:425)
    at net.minecraft.client.main.Main.main(Main.java:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
    Minecraft Version: 1.14.4
    Minecraft Version ID: 1.14.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_211, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3256838472 bytes (3105 MB) / 3928489984 bytes (3746 MB) up to 3928489984 bytes (3746 MB)
    CPUs: 4
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
    Fabric Mods: 
        blue_endless_jankson: jankson +
        cloth: Cloth Events 0.3.1+build.23
        cloth-config2: Cloth Config v2 1.0.0
        cmdkeybind: Command Macros 1.2.1
        fabric: Fabric API 0.3.1+build.208
        fabric-api-base: fabric-api-base 0.1.0+5914746355
        fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
        fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
        fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
        fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
        fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
        fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
        fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
        fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
        fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
        fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
        fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
        fabric-models-v0: fabric-models-v0 0.1.0+5914746342
        fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
        fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
        fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
        fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
        fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
        fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
        fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
        fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
        fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
        fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
        fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
        fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
        fabricloader: Fabric Loader 0.4.8+build.159
        lightoverlay: Light Overlay 3.4
        litematica: Litematica 0.0.0-dev.20190720.191654
        malilib: MaLiLib 0.10.0-dev.20
        modmenu: Mod Menu 1.7.9-unstable.19w34a+build.1
        mousewheelie: Mouse Wheelie 1.2.13+1.14.4
        orderly: Orderly 1.1.1+build.16
        tweed: Tweed API 2.2.2
        voxelmap: VoxelMap 1.9.13
    Launched Version: MultiMC5
    LWJGL: 3.2.2 build 10
    OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fabric'
    Type: Client (map_client.txt)
    Resource Packs: vanilla
    Current Language: English (US)
    CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\--------\Downloads\Games\Minecraft\MultiMC\instances\multimc\.minecraft\crash-reports\crash-2019-08-28_19.24.42-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
Clipboard copy at: 28 Aug 2019 19:24:48 +0100
Clipboard copy at: 28 Aug 2019 19:26:43 +0100
```

**Comment by Prospector** [comment]
You are using the 1.15 version on 1.14.4
