### ISSUE TITLE
mouseClicked event causes crash

### ISSUE THREAD

**Issue by thecreeper3326** [Prospector/ModMenu#699]
Okay, not that much of a coder but there has been a crash in a recent realese of the mod menu

here is the log entry that i think was linked to the crash:

i use fabric 1.20.4 
i can post installed mods if needed

[22:24:32] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.moulberry.axiom.editor.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:218) ~[Axiom-2.7.0-for-MC1.20.4.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[Axiom-2.7.0-for-MC1.20.4.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220) ~[client-intermediary.jar:?]

**Comment by N0tHorizon** [comment]
Client error, I don't have a solution but that's a client issue, try matching client and mod versions

**Comment by KorbynTalks** [comment]
Im having the same issue, ive been looking at the log for the error for way too long, and I cant find a solution.
