### ISSUE TITLE
Crashes on 24w18a when I click the menu of this mod

### ISSUE THREAD

**Issue by sdy623** [Prospector/ModMenu#729]
I tried to make the mod installed and successfully loaded in the latest 24w18a snapshot client. However, when I entered the mod menu, and try to edit the configuration of this mod. It crashes.
![image](https://github.com/TerraformersMC/ModMenu/assets/70808322/ee746db6-3fa2-41dd-9bc4-c8132eeffb1a)

<img width="1289" alt="image" src="https://github.com/TerraformersMC/ModMenu/assets/70808322/48a1d94b-e7b0-45d4-9508-8da395d0f075">

Here is the log [log](https://mclo.gs/MHOdmvP).
```
java.lang.NoSuchMethodError: 'void net.minecraft.class_353.<init>(net.minecraft.class_310, int, int, net.minecraft.class_4667)'
	at com.terraformersmc.modmenu.gui.ModMenuOptionsScreen.method_25426(ModMenuOptionsScreen.java:24)
	at net.minecraft.class_437.method_25423(class_437.java:318)
	at net.minecraft.class_310.method_1507(class_310.java:1141)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$4(ModsScreen.java:193)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:236)
	at net.minecraft.class_310.method_1523(class_310.java:1309)
	at net.minecraft.class_310.method_1514(class_310.java:880)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by haykam821** [comment]
This issue was fixed by porting the mod to Minecraft 1.21 pre-release 2 in #734.
