### ISSUE TITLE
lag for about 3s every time when you quit game

### ISSUE THREAD

**Issue by acaciachan** [Prospector/ModMenu#742]
[15:15:54] [Worker-Main-1/ERROR]: Error checking for updates: 
java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:553) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$4(ModrinthUtil.java:81) ~[modmenu-7.2.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by acaciachan** [comment]
in 1.21 this also happened

[17:52:55] [ModMenu/Update Checker/1/ERROR]: Error checking for versions: 
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:935) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133) ~[java.net.http:?]
	at com.terraformersmc.modmenu.util.HttpUtil.request(HttpUtil.java:24) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.util.UpdateCheckerUtil.getCurrentVersions(UpdateCheckerUtil.java:180) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.util.UpdateCheckerUtil.lambda$checkForUpdates0$1(UpdateCheckerUtil.java:87) ~[modmenu-11.0.1.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329) ~[?:?]
[17:52:55] [ModMenu/Update Checker/2/ERROR]: Error checking for updates: 
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:935) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133) ~[java.net.http:?]
	at com.terraformersmc.modmenu.util.HttpUtil.request(HttpUtil.java:24) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.util.UpdateCheckerUtil.getUpdatedVersions(UpdateCheckerUtil.java:256) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.util.UpdateCheckerUtil.lambda$checkForUpdates0$2(UpdateCheckerUtil.java:88) ~[modmenu-11.0.1.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329) ~[?:?]

**Comment by Cai-kunkun** [comment]
in 1.21.4 this also happened
![image](https://github.com/user-attachments/assets/3bbdfe91-899d-4236-9b64-23ea0800980d)

**Comment by MukjepScarlet** [comment]
I'll take a look about this too.
