### ISSUE TITLE
"Mod midnightlib provides a broken implementation of ModMenuApi"

### ISSUE THREAD

**Issue by WhyAreLess** [Prospector/ModMenu#759]
Hi! Thought I would drop this in. Apologies in advance if it's been fixed with later versions.

What launcher do I use? 
**Modrinth launcher with Minecraft version 1.20.4 and fabric loader 0.16.0**

Does the game crash? 
**No**

Does it happen every time you launch Minecraft?
**Yes**

Still able to use Mod Menu? 
**Yes**

Mod Menu version? 
**V9.20 for 1.20.4**

Error log: (if there are any better ways to give info in logs please let me know how and I'll get another log)
```
[16:23:42] [Render thread/ERROR]: Mod midnightlib provides a broken implementation of ModMenuApi
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'modmenu' provided by 'midnightlib'
at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.16.0.jar:?]

at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:92) ~[modmenu-9.2.0.jar:?]
at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:87) ~[modmenu-9.2.0.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.16.0.jar:?]
at net.minecraft.class_310.<init>(class_310.java:487) ~[client-intermediary.jar:?]
at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-0.16.0.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.0.jar:?]

Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: eu.midnightdust.lib.config.AutoModMenu
at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.0.jar:?]
	... 10 more

Caused by: java.lang.ClassNotFoundException: eu.midnightdust.lib.config.AutoModMenu
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
       ... 10 more
```

**Comment by WhyAreLess** [comment]
Is **MidnightLib** another mod library I should download to fix this,
 or is that mod unrelated to this as **Fabric API** and **Text Placeholder API** are the only dependencies?

**Comment by Prospector** [comment]
Has nothing to do with Mod Menu
