### ISSUE TITLE
Mod Menu depends on the monolith `fabric` rather than `fabric-resource-loader`

### ISSUE THREAD

**Issue by Sollace** [Prospector/ModMenu#82]
Because Mod Menu also depends on literally everything.

```[17:12:13] [main/INFO]: Loading for game Minecraft 1.15 Pre-release 6
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod modmenu depends on mod {fabric @ [*]}, which is missing!
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:309)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:84)
```

Please only depend on the things you use.

**Comment by Prospector** [comment]
Fixed in v1.8.1
